LoadPipe/Hamza-medusa

hamza-client/src/modules/layout/components/cart-dropdown/index.tsx

added a '/' in the proper place

Fix to resolve issue #18

---

hamza-server/medusa-config.js
hamza-server/package.json
hamza-server/src/api/admin/custom/user/route.ts
hamza-server/src/index.d.ts
hamza-server/src/migrations/1709191458615-UserandStore.ts
hamza-server/src/models/store.ts
hamza-server/src/models/user.ts
hamza-server/src/services/store.ts
hamza-server/src/services/user.ts

- Reversed the relationship of User and Store. "owner" is now a column on the "store" table and it exists as a onetoone relationship. 
- Added the addUser method to the storeService. Takes in a "User" as input and returns a newly created store with the user as "owner"
- Added a docker reset script for quickly clearing volumes and getting up and running again. 
- Implemented fix for password in the admin/custom/user api call

Staging vendor reverse relationship

---

hamza-client/next.config.js
hamza-server/data/seed-1.json
hamza-server/deepclean.sh
hamza-server/softclean.sh

This is just updating the seed to pull product images from the AWS server which serves images (which is on now), it's pulling the normal images (not the nounish ones), and a config change on the client to allow that image server.

Product images

---

hamza-server/package.json
hamza-server/src/index.d.ts
hamza-server/src/services/store.ts

propperly setting the owner.id

---

.github/workflows/ci.yml

CI Testing

---

hamza-client/src/modules/collections/product_collection_filter/index.tsx
hamza-client/src/modules/home/components/products/index.tsx
hamza-server/src/api/admin/products/create-product.ts

- Getting Products By Name Filter on Storefront

Staging tanstack products

---

hamza-server/data/seed.json
hamza-server/src/api/admin/custom/user/route.ts

- added real ETH addresses for users
- added 'crypto' by default as payment provider to both regions

Streamline setup

---

hamza-client/src/modules/checkout/components/payment-button/index.tsx
hamza-server/src/services/crypto-payment-provider.ts

As per the details, changed the returned wallet address from first element of the array to the array itself and handled the array in the client side in payment button component.

Staging crypto payment address

---

README.md
hamza-server/scripts/call-api.js
hamza-server/scripts/init-search-api.js
hamza-server/scripts/setup-0.sh

- added script to retrieve search API key (MeilliSearch) and put it into server & client env files 
- calling this script from setup-0
- no new setup steps 
- also added 'yarn up' to setup-0 process 
- updated README (clarified a bit)

Automate setup: Search API key

---

hamza-client/src/app/[countryCode]/(checkout)/checkout/page.tsx
hamza-client/src/app/[countryCode]/(checkout)/layout.tsx
hamza-client/src/modules/cart/components/empty-cart-message/index.tsx
hamza-client/src/modules/cart/components/sign-in-prompt/index.tsx
hamza-client/src/modules/cart/templates/index.tsx
hamza-client/src/modules/cart/templates/items.tsx
hamza-client/src/modules/checkout/components/addresses/index.tsx
hamza-client/src/modules/checkout/components/discount-code/index.tsx
hamza-client/src/modules/checkout/components/payment/index.tsx
hamza-client/src/modules/checkout/components/review/index.tsx
hamza-client/src/modules/checkout/components/shipping/index.tsx
hamza-client/src/modules/checkout/templates/checkout-summary/index.tsx
hamza-client/src/modules/collections/product_collection_filter/index.tsx
hamza-client/src/modules/collections/templates/index.tsx
hamza-client/src/modules/common/components/divider/index.tsx
hamza-client/src/modules/home/components/featured-products/product-rail/index.tsx
hamza-client/src/modules/home/components/products/index.tsx
hamza-client/src/modules/layout/components/cart-dropdown/index.tsx
hamza-client/src/modules/layout/components/medusa-cta/index.tsx
hamza-client/src/modules/products/components/product-actions/index.tsx
hamza-client/src/modules/products/components/product-price/index.tsx
hamza-client/src/modules/products/components/product-tabs/index.tsx
hamza-client/src/modules/products/components/related-products/index.tsx
hamza-client/src/modules/products/templates/index.tsx
hamza-client/src/modules/store/templates/index.tsx
hamza-client/src/styles/globals.css

- Dark Mode
- More responsive design w/ (simpleGrid and Flexbox's)

Staging styling

---

hamza-client/src/app/[countryCode]/(main)/wishlist/page.tsx
hamza-client/src/app/layout.tsx
hamza-server/package.json
hamza-server/scripts/armageddon.sh

- Fixed mis-cased import causing build issue
- Remove 'reset-dev-server' command (outdated) 
- Added "yarn ageddon" command

fix for build error: casing

---

hamza-client/src/modules/collections/product_collection_filter/index.tsx
hamza-server/src/api/store/custom/products/route.ts
hamza-server/src/services/product.ts

Show prices on homepage next to products
- created a new method on ProductService to get products with prices (may come in handy again)
- changed route that gets homepage products, to call that service instead
- added display logic in product collection component
Possible future work: 
- make the price display look nicer
- return custom object instead of Product, so as to save bandwidth (no need to return info on every variant & such)

Homepage prices

---

hamza-client/src/modules/cart/components/item/index.tsx
hamza-client/src/modules/cart/components/sign-in-prompt/index.tsx
hamza-client/src/modules/cart/templates/items.tsx
hamza-client/src/modules/layout/components/side-menu/index.tsx
hamza-client/src/modules/layout/templates/nav/index.tsx
hamza-client/src/modules/products/components/option-select/index.tsx
hamza-client/src/modules/products/components/product-actions/index.tsx
hamza-client/src/modules/products/templates/product-info/index.tsx

- made the background black for cart items 
- changed the text color of a hard-to-see line (in cart)
- removed Account links from menu 
- disabled Sign In button on cart
- changed style of Add to Wishlist button (hard to see)
- changed product variant/option select buttons to black 
- brightened up product title on product page

small UI tweaks

---

hamza-client/src/app/components/connect-button/connect-button.tsx
hamza-client/src/app/components/wishlist/wishlist-popover.tsx
hamza-client/src/modules/collections/product_collection_filter/index.tsx
hamza-client/src/modules/layout/components/cart-dropdown/index.tsx
hamza-client/src/modules/layout/templates/nav/index.tsx
hamza-client/src/store/wishlist/mutations/wishlist-mutations.tsx
hamza-client/src/store/wishlist/wishlist-store.tsx

- Changed places where 'localhost' was hard-coded (won't work on server) 
- Made some last minute UI tweaks, sometimes poorly (see commits)

Aws demo: Final tweaks & twerks

---

hamza-server/src/services/product-collection.ts

- fixed the create method (using save instead of update)

Fixed the create method for ProductCollectionService

---

hamza-server/data/seed.json
hamza-server/src/migrations/1904904849023-MultiVendorPrice.ts
hamza-server/src/models/price-list.ts
hamza-server/src/repositories/price-list.ts
hamza-server/src/services/price-list.ts

- migrations 
- service
- repository
- model
The usual pattern, nothing fancy

Associate Price List with Store

---

hamza-client/src/modules/checkout/components/payment-button/index.tsx
hamza-client/src/web3/master-switch-client.ts
hamza-server/src/api/custom/checkout/route.ts
hamza-server/src/migrations/1893867137584-MultiVendorPayment.ts
hamza-server/src/services/order.ts
hamza-server/src/strategies/cart-completion.ts

- updated payment with cart id 
- removed unique index from payment 
- updated payment.receiver_address before payment, instead of after 
- fixed the incorrect Switch address (not sure how that ever changed, or how it was even working) 
- a little tidying up

Checkout loose ends

---

currency-data/client/medusa-dist-utils/currencies.js
currency-data/client/utils-dist-defaults/currencies.js
currency-data/server/adminui-ui-src-utils/currencies.ts
currency-data/server/utils-dist-defaults/currencies.js
hamza-client/src/currency.config.ts
hamza-client/src/modules/checkout/components/payment-button/index.tsx
hamza-client/src/modules/collections/product_collection_filter/index.tsx
hamza-server/data/seed.json
hamza-server/src/migrations/1715010783066-BigNumber-money-amounts.ts

Adding larger int size to database, adding precision to the currency config and changing seed prices and amounts

---

hamza-client/src/currency.config.ts

adding zero address to currency config

---

hamza-client/src/currency.config.ts
hamza-client/src/lib/util/get-product-price.ts
hamza-client/src/lib/util/transform-product-preview.ts
hamza-client/src/modules/collections/product_collection_filter/index.tsx
hamza-client/src/modules/common/components/line-item-price/index.tsx
hamza-client/src/modules/common/components/line-item-unit-price/index.tsx
hamza-client/src/modules/order/components/order-summary/index.tsx
hamza-client/src/modules/products/components/product-preview/price.tsx
hamza-client/src/modules/products/components/product-price/index.tsx
hamza-server/data/seed.json

- realistic prices, and better mix of prices in seed
- client-side formatting of crypto prices (in many places - still not complete)
- created tasks for future completion of client-side price display

Price selection strategy

---

hamza-client/src/currency.config.ts
hamza-client/src/modules/checkout/components/payment-button/index.tsx
hamza-client/src/web3/master-switch-client.ts
hamza-client/src/web3/switch-client.ts

Correctly translate price from db to native precision

Staging amount translation boogy

---

hamza-client/src/currency.config.ts
hamza-client/src/lib/util/get-product-price.ts
hamza-client/src/modules/checkout/components/payment-button/index.tsx
hamza-client/src/web3/master-switch-client.ts
hamza-client/src/web3/switch-client.ts
hamza-server/data/seed.json

There were a few issues: 
- wrong prices in seed
- typo in currency.config 
- misconfiguration in currency.config

Currency display bug fix

---

hamza-client/src/app/[countryCode]/(main)/search/page.tsx
hamza-client/src/currency.config.ts
hamza-client/src/modules/search/templates/search-modal/index.tsx
hamza-server/src/api/custom/nonce/route.ts
hamza-server/src/models/customer.ts
hamza-server/src/services/customer.ts

- Added the /search route back in 
- Not sure what to do for closeModal - so just put in a try/catch for now
- Accidentally added the USDT change to this PR branch (sorry; both changes are small though, they can go together)

Fix Bug: Search Menu Broken Link

---

hamza-client/src/app/components/providers/rainbowkit/rainbow-provider.tsx

Used signOut function from medusa storefront package for log out

ci: changed customer logout

---

hamza-client/src/currency.config.ts
hamza-server/src/massmarket/client.ts

- added comments/cleanup to relay client wrapper 
- unrelated, changed the usdc address for sepolia to custom usdt, to ease testing problems

commented up the relay client

---

hamza-client/src/modules/cart/templates/index.tsx
hamza-client/src/modules/common/components/cart-totals/index.tsx
hamza-client/src/modules/common/components/line-item-price/index.tsx
hamza-client/src/modules/common/components/line-item-unit-price/index.tsx
hamza-client/src/modules/order/components/order-summary/index.tsx
hamza-server/src/migrations/1894875825785-LineItem.ts
hamza-server/src/strategies/cart-completion.ts

- Fixed a few stray places where price currency was still hard-coded in the UI 
- Fixed cart subtotals (one subtotal per currency) 
- Remove "Inventory" test button

Checkout prices: Cart totals display

---

hamza-server/src/migrations/1894875825785-LineItem.ts

Fixed incorrect field name in migration

Fixed incorrect field name in migration

---

hamza-client/src/currency.config.ts
hamza-client/src/lib/util/prices.ts
hamza-client/src/modules/common/components/line-item-price/index.tsx

- Created new USDC coin on sepolia
- Minted to the players
- Changed currency.config.ts accordingly

Usdc coin for Testing

---

hamza-client/src/app/components/providers/rainbowkit/rainbow-provider.tsx
hamza-client/src/modules/layout/components/cart-dropdown/index.tsx
hamza-client/src/modules/products/components/product-actions/index.tsx
hamza-client/src/store/wishlist/wishlist-store.tsx

Wishlist bug fix

---

hamza-client/src/modules/account/components/order-card/index.tsx
hamza-client/src/modules/products/components/product-actions/index.tsx

https://www.notion.so/hamza-market/Order-Amounts-0-17b0c4f9f591463eaf11361e3f400391?pvs=4

BUG: Order Amount 0

---

hamza-client/src/modules/home/components/hero/index.tsx
hamza-client/src/modules/home/components/products/index.tsx

All of the wallet buttons on homepage do the same as 'connect wallet' now.

Bug fix: Wallet buttons on homepage don't work

---

hamza-client/src/modules/order/components/order-summary/index.tsx

https://www.notion.so/hamza-market/Order-Details-Price-Format-a947a1fbe1704497b708904a0df3f02a?pvs=4

order details currency

---

hamza-server/src/services/__tests__/route.test.js
hamza-server/src/services/__tests__/simple.test.js
hamza-server/src/services/sum.js

Simple Jest Tests

---

hamza-client/src/modules/account/components/order-card/index.tsx
hamza-client/src/modules/order/components/items/index.tsx

Order && Order Details Image sizing: https://www.notion.so/hamza-market/Order-Details-Large-Prod-Images-2ddfb37eb52647cda85347af553d36ab?pvs=4

Sizing Fixes for order && order details

---

hamza-client/src/modules/layout/templates/nav/index.tsx
hamza-client/src/modules/products/components/product-actions/index.tsx
hamza-client/src/store/wishlist/wish.tsx
hamza-client/src/store/wishlist/wishlist-store.tsx

https://www.notion.so/hamza-market/Wishlist-for-Non-logged-in-user-b91e0e1dd9b74ce79a07b81dcacd377b?pvs=4

Ternary Wishlist for logged out user

---

hamza-server/scripts/call-api.js
hamza-server/src/api/admin/custom/massmarket/route.ts
hamza-server/src/massmarket/client.ts
hamza-server/src/massmarket/utils.ts
hamza-server/src/migrations/2849489248924-MassMarket.ts
hamza-server/src/models/product.ts
hamza-server/src/models/store.ts
hamza-server/src/services/store.ts

- migrations
- model changes 
- admin route to initially populate the ids in the database 
- setup script change to call the admin route

DB changes for MassMarket integration

---

hamza-client/src/app/components/providers/rainbowkit/connect-button/connect-button.tsx
hamza-client/src/store/wishlist/wishlist-store.tsx

wishlist ternary fix? 
connect button disappear fix?

Wishlist ternary fix, connect button disappear fix?

---

hamza-client/src/modules/checkout/actions.ts
hamza-client/src/modules/checkout/components/shipping-address/index.tsx

- email input remains blank if contains 'EVM' address
- if blank then setAddress data object will not include email state, to avoid email error messages

Checkout email bug - update

---

hamza-client/src/modules/products/components/product-price/index.tsx
hamza-client/src/modules/products/components/product-review/index.tsx

- If no reviews, review box is empty and shows  “no reviews for this product yet”
- If no ratings, stars are hidden

Handle showing reviews

---

hamza-client/src/app/[countryCode]/(main)/account/@dashboard/editreview/[id]/page.tsx
hamza-client/src/modules/account/components/order-overview/index.tsx
hamza-client/src/modules/editreview/[id]/edit-review-template.tsx
hamza-client/src/modules/order/components/items/index.tsx
hamza-client/src/modules/order/templates/order-details-template.tsx
hamza-server/src/api/custom/review/update/route.ts
hamza-server/src/api/custom/vendors/route.ts
hamza-server/src/services/product-review.ts
hamza-server/src/services/store.ts
http-client/local-dev.http

Edit reviews

---

hamza-client/src/contracts.config.ts
hamza-client/src/currency.config.ts
hamza-client/src/modules/checkout/components/payment-button/index.tsx

- Switch and tokens deployed to optimism sepolia
- Contract addresses from config file (not hard-coded) 
- Updated currencies.config with op-sepolia tokens

Deployed everything to OP-Sepolia

---

hamza-client/src/modules/checkout/components/payment-button/index.tsx

Bug fix: Checkout was getting the wrong contract address (MM leaked into checkout)

Checkout bug fix

---

hamza-client/src/app/[countryCode]/(main)/page.tsx
hamza-client/src/modules/home/components/hero-banner/index.tsx
hamza-client/src/modules/home/components/product-layout/components/buy-button.tsx
hamza-client/src/modules/home/components/product-layout/components/cart-button.tsx
hamza-client/src/modules/home/components/product-layout/components/product-card.tsx
hamza-client/src/modules/home/components/product-layout/index.tsx
hamza-client/src/modules/home/components/reputation/index.tsx
hamza-client/src/modules/home/components/search-and-filter-panel/components/SearchBar.tsx
hamza-client/src/modules/home/components/search-and-filter-panel/index.tsx
hamza-client/src/modules/products/components/buy-button/index.tsx

- updated product cards
- add to cart button works
- add search bar ui
- buy button works
- added hero banner and as seen in banner
- improved responsiveness

Home  Page Update

---

hamza-server/src/api/custom/review/existing/route.ts
http-client/local-dev.http

Edit Review fix

---

hamza-client/src/modules/products/components/product-price/index.tsx
hamza-server/src/api/custom/get-store/route.ts
hamza-server/src/services/product.ts
http-client/local-dev.http

- https://www.notion.so/hamza-market/Vendor-Link-on-Product-Page-936ccb0a2ee94906b036d01d9f86796a?pvs=4

Vendor link on product page

---

hamza-server/.env.example
hamza-server/.gitignore

Adding these variables to env file will automatically start saving the logging
silly, debug, info, warn, error
These are the five types of logs currently handled in medusa
silly is for storing all kinds of logs

ci: added logging env and tested the same

---

hamza-client/src/app/components/providers/rainbowkit/connect-button/connect-button.tsx
hamza-client/src/modules/home/components/hero-banner/index.tsx
hamza-client/src/modules/home/components/product-layout/components/product-card.tsx
hamza-client/src/modules/home/components/product-layout/index.tsx
hamza-client/src/modules/home/components/reputation/index.tsx
hamza-client/src/modules/home/components/search-and-filter-panel/components/SearchBar.tsx
hamza-client/src/modules/home/components/search-and-filter-panel/index.tsx
hamza-client/src/modules/layout/templates/footer/index.tsx
hamza-client/src/modules/layout/templates/nav-update/index.tsx
hamza-client/src/modules/layout/templates/nav-update/nav-link/nav-link.tsx

- nav bar update, hamburger menu appears in mobile, added icons, updated cart button
- update to new footer design
- various css fixes
- fade in / out affiliate banner
- adjust comp max width dimensions
- product cards now link to product preview

Home Page Update

---

hamza-client/src/app/[countryCode]/(main)/page.tsx
hamza-client/src/modules/order/components/items/index.tsx

Change homepage title/description

Change homepage title/description

---

hamza-client/src/modules/home/components/search-and-filter-panel/components/SearchBar.tsx
hamza-client/src/modules/home/components/search-and-filter-panel/index.tsx

https://www.notion.so/hamza-market/Home-Page-Search-functionality-4-c098f2157f1a40008b229de6137d2886?pvs=4

Search Functionality added to new bar

---

hamza-client/src/app/components/providers/rainbowkit/rainbow-provider.tsx
hamza-client/src/app/components/providers/rainbowkit/rainbowkit-utils/rainbow-utils.tsx
hamza-client/src/modules/home/components/hero-banner/index.tsx

https://www.notion.so/hamza-market/No-warning-error-if-on-unsupported-chain-8afc49c1124240e6af8c9f86cf8a735b?pvs=4

Chain error

---

hamza-server/src/services/confirmation-token.ts
hamza-server/src/services/smtp-mail.ts
hamza-server/src/services/smtp-notification-provider.ts
hamza-server/views/order-placed.ejs
hamza-server/views/verify-email.ejs

Made the email templates look better (better text)

Fixed email templates

---

hamza-client/src/modules/home/components/products/index.tsx
hamza-client/src/modules/home/components/search-and-filter-panel/data/data.ts
hamza-client/src/modules/home/components/search-and-filter-panel/index.tsx
hamza-client/src/modules/store-v2/component/store-filter-display.tsx
hamza-client/src/modules/store-v2/component/store-side-menu.tsx
hamza-client/src/modules/store-v2/index.tsx
hamza-server/data/products.csv
hamza-server/scripts/import-products.js
hamza-server/scripts/setup-1.sh
hamza-server/src/api/admin/custom/product/route.ts
hamza-server/src/api/admin/custom/user/route.ts

Created an ingenious unprecedented system using the latest research in CSV tech, by which developers can add new products to a .csv file, and those products will end up getting imported to the database when setup runs. 
Also added some new users & stores in setup.

Demo stores and products

---

hamza-client/src/modules/products/components/product-preview/components/preview-checkout.tsx
hamza-client/src/modules/products/components/product-preview/components/preview-gallery.tsx

Client build fixes

---

hamza-client/src/modules/layout/templates/footer/index.tsx
hamza-server/src/api/admin/custom/user/route.ts
http-client/local-dev.http

https://www.notion.so/hamza-market/Medusa-Merch-store-not-showing-up-in-Store-fe97f0cd61774b4e9565504427700e03?pvs=4

Medusa Merch store not showing up in Store

---

hamza-client/src/app/[countryCode]/(main)/products/[handle]/page.tsx
hamza-client/src/modules/editreview/[id]/edit-review-template.tsx
hamza-client/src/modules/home/components/product-layout/components/product-card.tsx
hamza-client/src/modules/home/components/product-layout/index.tsx
hamza-client/src/modules/products/components/product-card-group/index.tsx
hamza-client/src/modules/products/components/product-card/index.tsx
hamza-client/src/modules/products/components/product-preview/components/preview-checkout.tsx
hamza-client/src/modules/products/components/product-preview/components/vendor-banner.tsx
hamza-client/src/modules/products/templates/index.tsx
hamza-client/src/modules/review/[id]/review-template.tsx

Format product card prices as crypto.

Crypto price format on product cards

---

hamza-server/src/subscribers/customer-verified-confirmation.ts
hamza-server/views/verify-confirmation.ejs

Updated the email template that gets sent after you've confirmed your account

updated email template for verify-confirmation

---

hamza-client/src/app/[countryCode]/(main)/account/@dashboard/addresses/page.tsx
hamza-client/src/app/[countryCode]/(main)/account/@dashboard/notifications/page.tsx
hamza-client/src/app/[countryCode]/(main)/account/@dashboard/reviews/page.tsx
hamza-client/src/middleware.ts
hamza-client/src/modules/account/actions.ts
hamza-client/src/modules/account/components/order-overview/index.tsx
hamza-client/src/modules/checkout/actions.ts
hamza-client/src/modules/checkout/components/addresses/index.tsx
hamza-client/src/modules/checkout/components/payment-button/index.tsx
hamza-client/src/modules/products/components/product-actions/index.tsx
hamza-client/src/modules/products/components/product-preview/components/preview-checkout.tsx

non-us country code for shipping can cause an issue. If FORCE_US_COUNTRY is set in .env in hamza-client, then it will force all country codes to be 'us'. To avoid that issue for the demo.

Enforce US country code

---

hamza-client/src/app/[countryCode]/(main)/page.tsx
hamza-client/src/app/[countryCode]/(main)/vendor/[slug]/page.tsx
hamza-client/src/modules/home/components/product-layout/index.tsx
hamza-client/src/modules/home/components/search-and-filter-panel/index.tsx
hamza-client/src/modules/products/components/product-preview/components/vendor-banner.tsx
hamza-client/src/modules/products/templates/index.tsx
hamza-client/src/modules/skeletons/components/skeleton-product-grid/index.tsx

Navigation to vendor

---

hamza-server/data/seed.json

Update the product image urls to the new https urls

product Image urls update

---

hamza-client/src/app/[countryCode]/(main)/products/[handle]/page.tsx
hamza-client/src/app/components/tweet/index.tsx
hamza-client/src/modules/home/components/hero-banner/index.tsx
hamza-client/src/modules/home/components/search-and-filter-panel/index.tsx
hamza-client/src/modules/products/templates/index.tsx

Tweet Component

---

hamza-client/src/modules/home/components/product-layout/components/product-card.tsx
hamza-client/src/modules/products/components/product-card/index.tsx

Currency was being formatted twice as crypto

fixed currency display on home & store pages

---

hamza-client/src/app/[countryCode]/(main)/vendor/[slug]/page.tsx
hamza-client/src/app/components/tweet/index.tsx
hamza-client/src/modules/account/components/order-overview/index.tsx
hamza-client/src/modules/order/components/order-details/index.tsx
hamza-client/src/modules/order/components/summary/index.tsx
hamza-client/src/modules/order/templates/order-completed-template.tsx
hamza-client/src/modules/products/templates/index.tsx
hamza-server/src/api/custom/order/complete-template/route.ts
hamza-server/src/api/custom/order/customer-orders/route.ts
hamza-server/src/services/order.ts
http-client/local-dev.http

https://www.notion.so/hamza-market/Report-Abuse-needs-Validation-509054a0633345a081e7398ab0cd8244?pvs=4

Report abuse

---

hamza-client/src/app/components/wishlist-dropdown/index.tsx
hamza-client/src/modules/home/components/reputation/index.tsx
hamza-client/src/modules/home/components/search-and-filter-panel/index.tsx
hamza-client/src/modules/layout/templates/footer/index.tsx

Prevented wishlist popover from happening when clicking the hearts.

commented out wishlist dropdown when adding to wishlist

---

hamza-client/src/modules/layout/templates/footer/index.tsx

Just what the title says, bro  - in the footer, where there was like a fake phone number and a weird greek-looking address and what not.

Shuffled some info around, removed fake info

---

hamza-client/src/modules/products/components/product-preview/components/product-info.tsx
hamza-server/data/seed.json
hamza-server/scripts/import-products.js
hamza-server/src/api/admin/custom/product/route.ts
hamza-server/src/api/admin/custom/user/route.ts

Some utilities to allow us to import better products more easily

Products import

---

hamza-server/data/seed.json
hamza-server/scripts/import-products.js
hamza-server/src/api/admin/custom/user/route.ts

utilities for entering better stores/products

---

hamza-client/src/lib/util/get-product-price.ts
hamza-client/src/modules/products/components/product-group-store/index.tsx
hamza-client/src/modules/products/components/product-preview/components/preview-checkout.tsx
hamza-client/src/modules/store-v2/component/product-card.tsx
hamza-server/src/utils/price-formatter.ts

More price format fixing; it keeps breaking, and I think there are still more places it needs to be fixed.

Homepage price fix

---

hamza-client/src/modules/checkout/components/payment-button/index.tsx
hamza-client/src/web3/massmarket-payment.ts
hamza-server/src/api/admin/custom/massmarket/route.ts
massmarket-rest-api/Tennessine/pnpm-lock.yaml
massmarket-rest-api/hamza/pnpm-lock.yaml
massmarket-rest-api/hamza/src/controllers/checkout.ts
massmarket-rest-api/hamza/src/controllers/test.ts
massmarket-rest-api/hamza/src/massmarket/client.ts
massmarket-rest-api/hamza/test-scripts/checkout-eth.sh

Fixed bug: not passing zero addr when checking out ETH 
Removed hard-coded values used during checkout: 
- store id 
- amounts 
- native amounts

Massmarket rest v2 Bug Fixes

---

hamza-client/src/modules/layout/templates/nav-v3/index.tsx
hamza-client/src/modules/store-v2/component/category-button.tsx
hamza-client/src/modules/store-v2/component/category-top-button.tsx
hamza-client/src/modules/store-v2/component/currency-button.tsx
hamza-client/src/modules/store-v2/component/mobile-fitler/components/category-modal-button.tsx
hamza-client/src/modules/store-v2/component/mobile-fitler/components/currency-modal-button.tsx
hamza-client/src/modules/store-v2/component/mobile-fitler/components/filter-modal.tsx
hamza-client/src/modules/store-v2/component/mobile-fitler/components/range-slider-modal.tsx
hamza-client/src/modules/store-v2/component/mobile-fitler/components/review-modal-button.tsx
hamza-client/src/modules/store-v2/component/product-card.tsx
hamza-client/src/modules/store-v2/component/range-slider.tsx
hamza-client/src/modules/store-v2/component/review-button.tsx

- Store Cards and Filter updates

Store Cards and Filter updates

---

hamza-client/src/modules/account/components/order-overview/index.tsx
hamza-server/data/seed.json

fixed image urls in seed, should be https not http
causes images to selectively show up on site

fixed image urls in seed, should be https not http

---

hamza-client/src/app/components/providers/rainbowkit/rainbowkit-utils/rainbow-utils.tsx
hamza-client/src/modules/home/components/hero-banner/index.tsx

Switch network thing is disabled, since it causes problems on mobile. I will handle checkout differently.

disabled switch network thing

---

hamza-client/src/modules/home/components/hero-banner/index.tsx
hamza-client/src/modules/home/components/search-and-filter-panel/components/SearchBar.tsx
hamza-client/src/modules/home/components/search-and-filter-panel/index.tsx
hamza-client/src/modules/layout/templates/nav-v3/index.tsx
hamza-client/src/modules/products/components/product-group-home/index.tsx
hamza-server/yarn.lock

- nav bar update
- banner update
- product layout update

Home mobile UI

---

hamza-client/src/modules/products/components/product-group-home/index.tsx

fixed client-side build error (type error)

---

hamza-server/src/api/admin/custom/massmarket/route.ts
massmarket-rest-api/hamza/src/controllers/checkout.ts
massmarket-rest-api/hamza/src/controllers/products.ts
massmarket-rest-api/hamza/src/controllers/store.ts
massmarket-rest-api/hamza/src/controllers/test.ts
massmarket-rest-api/hamza/src/massmarket/client.ts
massmarket-rest-api/hamza/src/routes/index.ts
massmarket-rest-api/hamza/test-scripts/addproducts.sh
massmarket-rest-api/hamza/test-scripts/create-store.sh
massmarket-rest-api/hamza/test-scripts/keycard.sh
massmarket-rest-api/hamza/test-scripts/listen.sh

- added code to listen for product add events 
- improved event listening 
- small fixes, improvements, and cleanups

Massmarket rest v2

---

hamza-client/src/web3/massmarket-payment.ts

This allows users who are not on the correct chain to still checkout successfully.

Faker checkout

---

hamza-client/src/app/components/providers/rainbowkit/rainbowkit-utils/rainbow-utils.tsx
hamza-client/src/modules/account/components/profile-currency/index.tsx
hamza-client/src/modules/products/templates/index.tsx

https://www.notion.so/hamza-market/WHen-on-Ethereum-net-Disconnect-doesn-t-show-up-d7bd9646c53944328a7c844e119e6368?pvs=4

added main chains for connect bug

---

hamza-client/src/app/[countryCode]/(main)/cart/page.tsx
hamza-client/src/modules/layout/components/cart-button/index.tsx
hamza-client/src/modules/products/components/product-group-home/index.tsx
hamza-client/src/modules/products/components/product-group-store/index.tsx
hamza-client/src/modules/products/components/product-preview/components/preview-checkout.tsx

Prices showing as zero sometimes (depending on some factors)
Fixed by ensuring that if no price is selected by currency, the first price is selected by default.

fix for zero-price on product card

---

hamza-client/src/modules/products/components/product-preview/components/preview-checkout.tsx

Star Rating Product Page

---

hamza-server/data/seed.json

... to be a little more realistic & varied

changed product prices

---

hamza-client/src/modules/home/components/search-and-filter-panel/components/filter-bar/FilterBar.tsx
hamza-client/src/modules/home/components/search-and-filter-panel/components/filter-bar/components/CategoryModalButton.tsx
hamza-client/src/modules/home/components/search-and-filter-panel/components/filter-bar/components/CurrencyModalButton.tsx
hamza-client/src/modules/home/components/search-and-filter-panel/components/filter-bar/components/FilterButton.tsx
hamza-client/src/modules/home/components/search-and-filter-panel/components/filter-bar/components/FilterModal.tsx
hamza-client/src/modules/home/components/search-and-filter-panel/components/filter-bar/components/ReviewModalButton.tsx
hamza-client/src/modules/home/components/search-and-filter-panel/components/filter-bar/data/cat-icons.ts
hamza-client/src/modules/home/components/search-and-filter-panel/components/filter-bar/data/crypto-currency-icons.ts
hamza-client/src/modules/home/components/search-and-filter-panel/components/filter-bar/data/currency-icons.ts

Home - Filter Modal

---

hamza-client/src/modules/home/components/search-and-filter-panel/data/data.ts
hamza-client/src/modules/home/components/search-and-filter-panel/index.tsx
hamza-client/src/modules/products/components/product-group-home/index.tsx
hamza-client/src/modules/products/components/product-group-store/index.tsx
hamza-client/src/modules/store-v2/component/store-side-menu.tsx
hamza-client/src/modules/store-v2/index.tsx
hamza-server/src/api/store/custom/all-products/route.ts
hamza-server/src/services/product.ts
http-client/local-dev.http

All products

---

hamza-client/src/modules/products/components/product-group-store/index.tsx
hamza-client/src/modules/store-v2/component/filter-bar-store.tsx
hamza-client/src/modules/store-v2/component/product-card.tsx
hamza-client/src/modules/store-v2/component/store-filter-display.tsx

- updated the top cat filter
- fixed wid th of product layout for cards

Store Page Layout + Filter

---

hamza-client/src/app/[countryCode]/(main)/layout.tsx

- fixed linear gradient
- fixed mobile product card layout on store

updated linear gradient

---

hamza-client/src/modules/home/components/search-and-filter-panel/index.tsx
hamza-client/src/modules/products/components/product-group-home/index.tsx
hamza-client/src/modules/store-v2/index.tsx

- fixed home modal filter and home page filer buttons
- fixed mobile for store product page

Home Filter fix

---

hamza-client/src/app/components/providers/rainbowkit/rainbowkit-utils/rainbow-utils.tsx

This Loading... div left over from the early days. It was not working properly; it shows permanently on homepage whenever user is not logged in. I removed it.

removed 'loading...' msg from homepage

---

hamza-client/src/web3/massmarket-payment.ts
hamza-server/src/api/custom/google/route.ts

Wait for the token approvals to be fully confirmed before attempting to transfer token during checkout. Not doing so occasionally causes checkout failure and emotional distress.

Token approval confirmation wait

---

hamza-client/src/modules/home/components/search-and-filter-panel/components/filter-bar/components/FilterModal.tsx
hamza-client/src/modules/layout/templates/nav-v3/components/nav-searchbar.tsx
hamza-client/src/modules/layout/templates/nav-v3/index.tsx
hamza-client/src/modules/products/components/product-group-home/index.tsx
hamza-client/src/modules/products/components/product-group-store/index.tsx
hamza-client/src/modules/store-v2/component/filter-bar-store.tsx
hamza-client/src/modules/store-v2/component/range-slider.tsx
hamza-client/src/modules/store-v2/component/store-side-menu.tsx
hamza-client/src/modules/store-v2/index.tsx

- implemented nav search
- store page updates
- various css updates

Nav Search + Store Page + Various Css

---

hamza-client/src/modules/home/components/search-and-filter-panel/components/filter-bar/FilterBar.tsx
hamza-client/src/modules/products/components/product-group-home/index.tsx

- fixed padding on top filter on home page and adjust dynamic width on

Home Page Styling

---

hamza-client/src/modules/checkout/components/shipping/index.tsx
hamza-server/data/seed.json

Shipping costs, as they appear in checkout, are now just hard-coded.

shipping costs hard-coded per currency & option type

---

hamza-client/public/images/buttons/filter-16px.svg
hamza-client/src/modules/home/components/hero-banner/index.tsx
hamza-client/src/modules/layout/components/cart-button-mobile/index.tsx
hamza-client/src/modules/layout/components/cart-dropdown-mobile/index.tsx
hamza-client/src/modules/layout/templates/nav-v3/components/mobile-menu.tsx
hamza-client/src/modules/layout/templates/nav-v3/components/mobile-nav.tsx
hamza-client/src/modules/layout/templates/nav-v3/index.tsx

Mobile Nav + Various css

---

hamza-client/src/modules/home/components/search-and-filter-panel/components/SearchBar.tsx
hamza-client/src/modules/layout/templates/nav-v3/components/nav-searchbar.tsx
hamza-client/src/modules/layout/templates/nav-v3/index.tsx
hamza-client/src/modules/products/components/product-preview/components/mobile-search.tsx
hamza-client/src/modules/products/templates/index.tsx
hamza-client/src/modules/store-v2/component/mobile-fitler/mobile-filter.tsx

tranistions and css updates

---

hamza-client/src/app/components/wishlist/index.tsx
hamza-client/src/modules/layout/templates/nav-v3/components/mobile-menu.tsx
hamza-client/src/modules/layout/templates/nav-v3/index.tsx

https://www.notion.so/hamza-market/Div-spacing-for-Wishlist-Non-Logged-in-407b329aa32f44e3b74924e84e7ced4b?pvs=4

Div spacing for Wishlist Non Logged in

---

hamza-client/src/modules/products/components/product-group-home/component/home-product-card.tsx
hamza-client/src/modules/store-v2/component/product-card.tsx

Show the currency next to the price on product cards (homepage & store page)

Homepage currency

---

hamza-client/src/modules/layout/templates/nav-v3/components/mobile-menu.tsx
hamza-client/src/modules/layout/templates/nav-v3/index.tsx

Links for "sell on hamza" menu items

Sell on hamza

---

hamza-client/src/modules/cart/actions.ts
hamza-server/src/api/custom/wishlist/route.ts
hamza-server/src/services/wishlist.ts

Before creating wishlist, check for existence of customer. No longer attempting to create it if customer doesn't exist.

check for customer id before adding wishlist

---

hamza-client/src/app/components/wishlist-dropdown/WishlistItem.tsx

html rendering for wishlist page

---

hamza-client/src/modules/cart/templates/summary.tsx
hamza-client/src/modules/checkout/components/addresses/index.tsx
hamza-client/src/modules/checkout/components/payment-button/index.tsx
hamza-client/src/modules/checkout/components/payment/index.tsx
hamza-client/src/modules/checkout/components/shipping/index.tsx
hamza-client/src/modules/checkout/components/submit-button/index.tsx
hamza-client/src/modules/checkout/templates/checkout-form/index.tsx
hamza-client/src/modules/home/components/search-and-filter-panel/components/filter-bar/FilterBar.tsx
hamza-client/src/modules/home/components/search-and-filter-panel/components/filter-bar/components/FilterButton.tsx
hamza-client/src/styles/globals.css

- clicking carousel button no longer highlights components
- added hover to filter button
- updated checkout buttons and back to shopping button

Design Updates - checkout buttons, filter button, back button

---

hamza-server/views/order-placed.ejs
hamza-server/views/verify-confirmation.ejs
hamza-server/views/verify-email.ejs

Added logo to bottom of email templates; Outgoing emails will show the logo and have a consistent format.

added closing with logo to each email template

---

hamza-server/data/seed.json

more realistic product pricing

---

hamza-client/src/modules/products/components/product-preview/components/product-review-mobile.tsx
hamza-client/src/modules/products/components/product-preview/components/product-review.tsx
hamza-client/src/modules/products/components/product-preview/components/review-card-mobile.tsx

- Changed the lorem ipsum text for fake reviews to actual english text. 
- Removed big white circle 
- Changed confusing text of avg. stars

Review improvements

---

hamza-client/src/modules/products/components/product-preview/components/review-card.tsx

Small design tweaks
Stars instead of a number (for avg. reviews) 
Removed white circle

Further review improvements

---

hamza-client/src/app/[countryCode]/(main)/layout.tsx
hamza-client/src/modules/home/components/search-and-filter-panel/components/filter-bar/FilterBar.tsx

- cleaned up home mobile slider button

Home Mobile Slider Button

---

hamza-client/src/modules/get-object-fit.ts
hamza-client/src/modules/products/components/product-group-home/component/home-product-card.tsx
hamza-client/src/modules/store-v2/component/product-card.tsx

Quick fix by hardcoding the objectFit and background color for specific products on the front end.

quick-fix for funky product images

---

hamza-server/data/seed.json

Modified weights in seed to control how images appear (ordering) on the homepage

ordering of homepage images

---

hamza-client/src/app/[countryCode]/(main)/account/@dashboard/profile/page.tsx
hamza-client/src/modules/account/components/profile-currency/index.tsx
hamza-client/src/modules/account/components/profile-name/index.tsx

Changed the background/foreground colors on form controls, because on some platforms the text is invisible.

changed color of account form widgets to make the text more visible

---

hamza-client/src/app/components/wishlist-dropdown/WishlistItem.tsx
hamza-client/src/modules/checkout/components/payment/index.tsx
hamza-client/src/modules/checkout/components/shipping/index.tsx
massmarket-rest-api/hamza/src/controllers/checkout.ts

- removed the need to choose 'crypto' (it's chosen as default) for payment method, since it's the only payment method
- fixed a small bug with fake checkout, in massmarket-rest-api checkout controller
-

removed the need for the choosing of 'crypto' as payment method

---

hamza-client/src/app/[countryCode]/(main)/layout.tsx
hamza-client/src/modules/store-v2/component/filter-bar-store.tsx
hamza-client/src/modules/store-v2/component/store-filter-display.tsx

- added filter button to store, although its not 100% the current demo does not have this functionality in store

updated store filter button

---

hamza-client/src/modules/cart/templates/items.tsx
hamza-client/src/modules/home/components/hero-banner/index.tsx

- Hero Banner loads instantly - Hydration bandaid was used due to windows object causing an error. Since we are no longer using this I removed the fix so the hero banner loads instantly.
- removed padding on cart so that its mobile responsive

Design tweaks - banner + cart

---

hamza-client/src/modules/editreview/[id]/edit-review-template.tsx
hamza-client/src/modules/products/components/product-card/index.tsx
hamza-client/src/modules/products/components/product-preview/components/preview-gallery.tsx
hamza-client/src/modules/review/[id]/review-template.tsx

Implemented the custom way of getting the correct object fit for product images on the product details page, and another place
Implemented html rendering for places that display the product description (which can be html)

Product image display (object fit)

---

hamza-client/src/modules/layout/templates/footer/index.tsx

Fixed the link that lets people join the discord

fixed follow us on discord link

---

hamza-client/src/modules/products/components/product-preview/components/preview-gallery.tsx

Corrected background color of main prod image on prodd preview (details) page

Product image

---

hamza-client/src/modules/products/components/cart-popup/index.tsx
hamza-client/src/modules/products/components/product-preview/components/preview-checkout.tsx

- fixed grammar on added to cart modal 
- made add to cart modal disappear after 3 seconds
- don't show added to cart modal on "buy now" action

Added to cart popup 

---

hamza-client/src/app/layout.tsx
hamza-client/src/styles/chakra-theme.ts

Root SSR since root should be ssr

Setting Root Layout to SSR

---

hamza-client/src/app/components/providers/rainbowkit/connect-button/connect-button.tsx
hamza-client/src/modules/layout/templates/nav-4/menu/components/authorized-account.tsx

client-side build errors (type)

clientside build fixes

---

hamza-client/src/app/error.tsx

The ol' catch-all global error page. Every site still needs one. Remember when sites didn't need one? I don't.

added error page

---

hamza-server/babel.config.js
hamza-server/package.json
hamza-server/src/services/__tests__/store.ts

Store Service Mock Repo Test

---

hamza-server/src/api/custom/order/all-orders/route.ts
hamza-server/src/api/custom/order/cancel/route.ts
hamza-server/src/api/custom/order/complete-template/route.ts
hamza-server/src/api/custom/order/customer-orders/route.ts
hamza-server/src/api/custom/order/order-details/route.ts
hamza-server/src/api/custom/order/status/route.ts
hamza-server/src/api/custom/order/vendor/route.ts

Just removed some comments; getting ready to find a place for a new order route

Order route: comment removal

---

hamza-client/src/app/[countryCode]/(main)/account/layout.tsx
hamza-client/src/modules/account-update/actions.ts
hamza-client/src/modules/account-update/components/account-info/index.tsx
hamza-client/src/modules/account-update/components/account-nav/components/nav-link.tsx
hamza-client/src/modules/account-update/components/account-nav/index.tsx
hamza-client/src/modules/account-update/components/address-book/index.tsx
hamza-client/src/modules/account-update/components/address-card/add-address.tsx
hamza-client/src/modules/account-update/components/address-card/edit-address-modal.tsx
hamza-client/src/modules/account-update/components/login/index.tsx
hamza-client/src/modules/account-update/components/notification-toggle/toggles.tsx
hamza-client/src/modules/account-update/components/notifications/index.tsx
hamza-client/src/modules/account-update/components/order-card/index.tsx
hamza-client/src/modules/account-update/components/order-overview/index.tsx
hamza-client/src/modules/account-update/components/overview/index.tsx
hamza-client/src/modules/account-update/components/profile-billing-address/index.tsx
hamza-client/src/modules/account-update/components/profile-currency/index.tsx
hamza-client/src/modules/account-update/components/profile-email/index.tsx
hamza-client/src/modules/account-update/components/profile-name/index.tsx
hamza-client/src/modules/account-update/components/profile-password/index.tsx
hamza-client/src/modules/account-update/components/profile-phone/index.tsx
hamza-client/src/modules/account-update/components/register/index.tsx
hamza-client/src/modules/account-update/components/review-page/index.tsx
hamza-client/src/modules/account-update/components/reviews/index.tsx
hamza-client/src/modules/account-update/templates/account-layout.tsx
hamza-client/src/modules/account-update/templates/login-template.tsx

Customer Account Update

---

hamza-client/src/modules/account-update/components/account-nav/index.tsx
hamza-client/src/modules/account/components/account-nav/index.tsx
hamza-client/src/modules/account/components/notification-toggle/toggles.tsx
hamza-client/src/styles/chakra-theme.ts

UX fixes: 
- Notification Page (disable button function && style)
- Logout Redirect fixes

Notification styling

---

hamza-server/src/api/custom/order/customer-orders/route.ts

small fixes, check for customer existence

---

hamza-client/src/app/[countryCode]/(main)/account/@dashboard/addresses/page.tsx
hamza-client/src/modules/account/components/address-card/add-address.tsx
hamza-client/src/modules/account/components/address-card/edit-address-modal.tsx
hamza-client/src/modules/checkout/components/country-select/index.tsx
hamza-client/src/modules/common/components/input/index.tsx
hamza-client/src/modules/common/components/modal/index.tsx
hamza-client/src/modules/common/components/native-select/index.tsx

Address update

---

hamza-client/src/modules/layout/templates/nav-4/menu/account-menu.tsx

Changed the destination of the 'settings' link in menu dropdown

settings and profile are the same thing

---

.gitignore
hamza-client/src/app/[countryCode]/(main)/account/@dashboard/profile/page.tsx
hamza-client/src/app/[countryCode]/(main)/account/@dashboard/profile/profile-form/profile-form.tsx
hamza-client/src/app/[countryCode]/(main)/account/@dashboard/verify/page.tsx
hamza-client/src/app/[countryCode]/(main)/account/layout.tsx
hamza-client/src/app/[countryCode]/(main)/verify-email/page.tsx
hamza-client/src/modules/account-update/components/account-nav/components/nav-link.tsx
hamza-client/src/modules/account-update/components/account-nav/index.tsx
hamza-client/src/modules/account/components/account-nav/components/nav-link.tsx
hamza-client/src/modules/account/components/account-nav/index.tsx
hamza-client/src/modules/account/components/verify/index.tsx
hamza-client/src/modules/account/templates/account-layout.tsx
hamza-client/src/modules/layout/templates/nav-4/menu/account-menu.tsx
hamza_dev_db@localhost.session.sql

- now in menu and account page

Verify link

---

hamza-client/src/app/[countryCode]/(main)/account/@dashboard/profile/page.tsx
hamza-client/src/app/[countryCode]/(main)/account/@dashboard/profile/profile-form/components/profile-image.tsx
hamza-client/src/app/[countryCode]/(main)/account/@dashboard/profile/profile-form/components/profile-input.tsx
hamza-client/src/app/[countryCode]/(main)/account/@dashboard/profile/profile-form/profile-form.tsx
hamza-client/src/lib/util/isCryptoAddress.ts

- fixed email input showing crypto address
- fixed profile data not refreshing

Profile email and data bug

---

hamza-client/src/app/[countryCode]/(main)/account/@dashboard/profile/profile-form/profile-form.tsx
hamza-client/src/modules/account/actions.ts
hamza-client/src/modules/account/components/address-card/add-address.tsx
hamza-client/src/modules/account/components/address-card/edit-address-modal.tsx

- added toast for success / error on components
- cleaned up address modal

Added toast to profile and addresses - cleaned up address modal

---

hamza-client/src/app/[countryCode]/(main)/account/@dashboard/profile/profile-form/profile-form.tsx

- email address hidden completely if not verified
- email address shown only as text (not editable ever)

hide email address, show only as text

---

hamza-client/src/app/actions.ts
hamza-client/src/app/components/providers/rainbowkit/rainbowkit-utils/rainbow-utils.tsx
hamza-client/src/modules/checkout/components/payment-button/index.tsx
hamza-client/src/modules/layout/templates/nav-4/components/mobile-nav.tsx
hamza-server/src/strategies/cart-completion.ts

- Replaced windows.ethreum with wagmi hook "useWalletConnect" as the wallet provider

Replaced windows.ethreum with wagmi hook "useWalletConnect"

---

hamza-client/src/contracts.config.ts
hamza-client/src/currency.config.ts
hamza-server/src/currency.config.ts

Preparing for imminent deployment to Optimism

contract and token addresses for optimism

---

hamza-client/src/modules/account-update/components/account-nav/index.tsx
hamza-client/src/modules/account/components/account-nav/index.tsx
hamza-client/src/modules/layout/templates/nav-4/menu/account-menu.tsx

- Verified accounts do not show account link on account menu and user settings

Verified accounts do not show account link

---

hamza-client/src/app/components/providers/rainbowkit/rainbowkit-utils/rainbow-utils.tsx
hamza-client/src/currency.config.ts
hamza-client/src/modules/home/components/hero-banner/index.tsx

Configuration for supported chains
Needs followup tasks to make it really effective
new .env variables for hamza-client (both optional) 
NEXT_PUBLIC_FORCE_SWITCH_BLOCKCHAIN 1 or nothing
NEXT_PUBLIC_ALLOWED_BLOCKCHAINS comma-delimited list of decimal chain ids

Supported chain config

---

hamza-client/src/modules/account-update/components/order-overview/index.tsx
hamza-client/src/modules/account/components/order-overview/index.tsx
hamza-client/src/modules/order/templates/all.tsx
hamza-client/src/modules/order/templates/processing.tsx

- added chaining operator to order array which fixed bug

Order crash bug

---

hamza-client/src/app/[countryCode]/(main)/account/@dashboard/profile/profile-form/profile-form.tsx
hamza-client/src/modules/account/components/profile-currency/index.tsx

- added preferred-currency to profile form

Added preferred currency component to profile user settings

---

hamza-client/src/app/components/providers/rainbowkit/rainbowkit-utils/rainbow-utils.tsx
hamza-client/src/modules/home/components/hero-banner/index.tsx
hamza-client/src/modules/layout/templates/nav-4/connect-button/components/connect-button.tsx
hamza-client/src/modules/layout/templates/nav-4/index.tsx

- switch component now works as attended
- please add NEXT_PUBLIC_ALLOWED_BLOCKCHAINS to env.local and set to Sepolia Network "11155111"

Switchnetwork noteffective bug

---

hamza-client/src/contracts.config.ts

Just added contract address config

Added contract address for Optimism switch

---

hamza-client/src/app/components/providers/rainbowkit/rainbowkit-utils/rainbow-utils.tsx

- prompt now dynamic depending on environment

Switchnetwork prod / dev dynamic modal

---

hamza-client/src/app/components/providers/rainbowkit/rainbowkit-utils/rainbow-utils.tsx
hamza-client/src/modules/checkout/components/payment-button/index.tsx

- fixed switch comp from popping up when already connected to desired network
- fixed connect prompt from popping up if already connected during payment

Switch and connect fix

---

hamza-client/src/app/[countryCode]/(main)/account/@dashboard/profile/page.tsx
hamza-client/src/app/[countryCode]/(main)/account/@dashboard/profile/profile-form/components/profile-image.tsx
hamza-client/src/app/[countryCode]/(main)/account/@dashboard/profile/profile-form/components/profile-input.tsx
hamza-client/src/app/[countryCode]/(main)/account/@dashboard/profile/profile-form/profile-form.tsx
hamza-client/src/modules/account/components/account-nav/index.tsx
hamza-client/src/modules/account/components/profile-currency/index.tsx
hamza-client/src/modules/account/templates/account-layout.tsx

- made profile page responsive for mobile
- made layout of profile settings dynamic

Account settings responsive update

---

hamza-client/src/app/components/providers/rainbowkit/rainbowkit-utils/rainbow-utils.tsx
hamza-client/src/web3.config.ts

Fixed race condition leading to SwitchNetwork modal sometimes appearing when it shouldn't
Added more logging for wallet issues

Wallet app update

---

hamza-client/src/app/[countryCode]/(checkout)/not-found.tsx
hamza-client/src/app/[countryCode]/(main)/not-found.tsx

- Updated alternative 404 error pages for main and checkout

Updated alternative 404 error pages

---

hamza-client/src/app/components/providers/rainbowkit/connect-button/connect-button.tsx
hamza-client/src/app/components/providers/rainbowkit/rainbowkit-utils/rainbow-utils.tsx
hamza-client/src/modules/checkout/components/payment-button/payment-handlers.ts
hamza-client/src/modules/layout/templates/nav-4/components/mobile-nav.tsx
hamza-client/src/modules/layout/templates/nav-4/connect-button/index.tsx
hamza-client/src/modules/layout/templates/nav-4/connect-mobile/components/connect-button.tsx
hamza-client/src/modules/products/components/product-group-home/index.tsx

The dusty plain bakes under the hot sun. Not a creature moves. 
Illusory heat waves stir the horizon like a mirage. 
On the promontory steps The Wallet Wrangler, six-gun by his side. 
He's ready for some shit.

The wallet wrangler

---

hamza-server/scripts/call-api.js
hamza-server/src/api/admin/custom/product/route.ts
hamza-server/src/api/admin/custom/user/route.ts
hamza-server/src/api/admin/custom/whitelist/route.ts
hamza-server/src/models/whitelist.ts
hamza-server/src/services/whitelist.ts
hamza-server/src/strategies/checkout-processors/basic-checkout.ts

Whitelist is created & setup up with addresses upon app setup

Whitelist setup

---

hamza-client/src/modules/cart/components/address/index.tsx
hamza-client/src/modules/checkout/components/addresses/index.tsx

Checks for null/undefined on certain properties

checkout null checks

---

hamza-client/src/modules/cart/components/address/index.tsx

Fixed two more instances of shipping addresses being empty (bug fix: checking first for empty shipping addresses array)

two more fixes for empty shipping addresses

---

hamza-client/src/modules/cart/templates/index.tsx
hamza-client/src/modules/checkout/components/addresses/index.tsx
hamza-client/src/modules/checkout/components/payment-button/index.tsx
hamza-client/src/modules/home/components/hero-banner/index.tsx
hamza-client/src/modules/order/components/order-details/index.tsx
hamza-client/src/modules/order/templates/order-completed-template.tsx

- Success page + toast on checkout + banner

Success page + toast on checkout + banner

---

hamza-client/src/modules/checkout/components/shipping/index.tsx

Prices displayed for fake shipping options are now 0.00

Zero shipping price

---

hamza-client/src/modules/products/components/product-preview/components/preview-checkout.tsx

Bug fix: wrong price showing on prod page if not logged in

bug fix: wrong prod page price

---

hamza-client/src/modules/cart/components/item/index.tsx
hamza-client/src/modules/cart/templates/index.tsx
hamza-client/src/modules/checkout/templates/checkout-summary/index.tsx
hamza-client/src/modules/common/components/line-item-price/index.tsx
hamza-client/src/modules/home/components/hero-banner/index.tsx
hamza-client/src/modules/layout/templates/nav-4/index.tsx
hamza-client/src/modules/order/components/order-details/index.tsx
hamza-client/src/modules/order/components/summary/index.tsx
hamza-client/src/modules/order/templates/order-completed-template.tsx

- updated nav logo
- updated cta message
- made affiliate look good on mobile
- fixed cart image dimensions
- fixed mobile cart responsiveness

Nav logo, CTA and mobile affiliate link update

---

hamza-client/src/modules/order/components/payment-details/index.tsx
hamza-client/src/modules/order/components/summary/index.tsx
hamza-client/src/modules/order/components/transaction-details/index.tsx
hamza-client/src/modules/order/templates/order-completed-template.tsx

New success page update

---

hamza-client/package.json
hamza-server/package.json

Starting software versioning for client & server

Versioning

---

hamza-server/src/api/custom/bucky/route.ts
hamza-server/src/api/custom/bucky/shipping/route.ts
hamza-server/src/api/custom/bucky/track/route.ts
hamza-server/src/buckydrop/bucky-client.ts
hamza-server/src/services/buckydrop.ts
hamza-server/src/services/product.ts

- Refactored & improved buckydrop import 
- Integrated buckydrop checkout

Bucky drop Import and Checkout

---

hamza-client/src/lib/data/index.ts
hamza-client/src/modules/checkout/components/addresses/index.tsx
hamza-client/src/modules/checkout/components/shipping-address/index.tsx
hamza-client/src/modules/checkout/components/shipping/index.tsx
hamza-server/data/seed.json
hamza-server/src/api/custom/bucky/route.ts
hamza-server/src/api/custom/bucky/track/route.ts
hamza-server/src/api/custom/cart/cancel/route.ts
hamza-server/src/api/custom/order/cancel/route.ts
hamza-server/src/buckydrop/bucky-client.ts
hamza-server/src/services/bucky-fulfillment.ts
hamza-server/src/services/buckydrop.ts
hamza-server/src/services/order.ts
hamza-server/src/services/product.ts
http-client/local-dev.http

- Improved import: more robust but slower 
- Added cancellation backend functionality
- Added backend functionality for tracking 
- New payment provider specifically for Buckydrop 
- Other improvements, bug fixes, refactoring, cleanup

Bucky drop

---

hamza-client/src/modules/common/components/cart-totals/index.tsx
hamza-client/src/modules/order/components/transaction-details/index.tsx

Cart totals display, adding up shipping costs

price displays for cart & thankyou page

---

hamza-client/src/modules/checkout/actions.ts
hamza-client/src/modules/checkout/components/payment-button/index.tsx
hamza-client/src/modules/order/components/summary/index.tsx
hamza-client/src/modules/order/templates/order-completed-template.tsx

Some loose ends from last PR, to enable correct scores on order confirmation page

fixed totals on thankyou page

---

hamza-client/src/app/[countryCode]/(main)/vendor/[slug]/page.tsx
hamza-client/src/modules/account/components/order-overview/index.tsx
hamza-client/src/modules/order/templates/all.tsx
hamza-client/src/modules/products/components/product-group-vendor/index.tsx
hamza-client/src/modules/vendors/components/products/vendor-cat-button.tsx
hamza-client/src/modules/vendors/components/products/vendor-product-display.tsx
hamza-client/src/modules/vendors/components/products/vendor-search.tsx
hamza-server/src/api/custom/order/cancel/route.ts
http-client/local-dev.http

Vendor design update

---

hamza-client/src/app/[countryCode]/(main)/order/confirmed/[id]/page.tsx

search params and cart for order conf. page

---

hamza-client/src/app/[countryCode]/(main)/vendor/[slug]/page.tsx

Fixed - The stats border were not lining up and causing overflow issues when minimizing screen

Fixed alignment issue

---

hamza-server/data/seed.json
hamza-server/scripts/call-api.js
hamza-server/src/api/custom/bucky/import/route.ts
hamza-server/src/api/custom/bucky/route.ts
hamza-server/src/api/custom/bucky/setup/route.ts
hamza-server/src/buckydrop/bucky-client.ts
hamza-server/src/services/bucky-fulfillment.ts
hamza-server/src/services/buckydrop.ts
hamza-server/src/strategies/cart-completion.ts
hamza-server/src/strategies/checkout-processors/basic-checkout.ts
hamza-server/src/strategies/price-selection.ts

- Shipping costs calculated automatically by a new shipping (fulfillment) provider specifically for Buckydrop
- New setup-1 api call to set up the fulfillment provider 
- Change to seed (so you will have to re-run setup-0) 
- Moved some of the bucky routes, and changed parameter types
- Changes to setup-1

Bucky drop: Fulfillment Provider

---

hamza-client/src/modules/vendors/components/products/vendor-product-display.tsx
hamza-client/src/modules/vendors/components/products/vendor-search.tsx
hamza-server/src/api/custom/store/categories/route.ts
hamza-server/src/api/custom/vendors/vendor-products/route.ts
hamza-server/src/services/product.ts

- updated product service to retrieve categories
- implemented inside vendor search
- tested on front end and it pulls in the backend

Vendor-product service-get category update backend

---

hamza-client/src/app/components/tweet/index.tsx
hamza-client/src/modules/order/components/summary/index.tsx
hamza-client/src/modules/order/templates/order-completed-template.tsx

- added x tweet back / fixed hydration error caused by svg (imported react-icon image)
- added check order status button

Thank you page - update

---

hamza-client/src/modules/order/components/cancel-order-modal/index.tsx
hamza-client/src/modules/order/templates/all.tsx

- refactor cancel request modal
- fixed axios error
- fixed modal close error

Order Overview Update

---

hamza-client/src/lib/util/get-product-price.ts
hamza-client/src/modules/cart/components/item-checkout/index.tsx
hamza-client/src/modules/cart/components/item/index.tsx
hamza-client/src/modules/cart/templates/index.tsx
hamza-client/src/modules/cart/templates/items-checkout.tsx
hamza-client/src/modules/cart/templates/items.tsx
hamza-client/src/modules/cart/templates/preview.tsx
hamza-client/src/modules/checkout/templates/checkout-summary/index.tsx
hamza-client/src/modules/common/components/cart-totals/index.tsx
hamza-client/src/modules/common/components/line-item-price/index.tsx
hamza-client/src/modules/common/components/line-item-unit-price/index.tsx
hamza-client/src/modules/layout/components/cart-dropdown/index.tsx
hamza-client/src/modules/layout/components/cart-nav/components/cart-button.tsx
hamza-client/src/modules/order/components/item/index.tsx
hamza-client/src/modules/order/components/order-summary/index.tsx
hamza-client/src/modules/order/components/transaction-details/index.tsx
hamza-server/src/services/buckydrop.ts
hamza-server/src/services/cart.ts
hamza-server/src/services/order.ts
hamza-server/src/strategies/price-selection.ts

Dynamic pricing

---

hamza-server/src/api/custom/bucky/import/route.ts
hamza-server/src/api/custom/bucky/track/route.ts

makes import easier on servers

added store parameter to bucky import route

---

hamza-client/src/modules/cart/templates/index.tsx
hamza-client/src/modules/cart/templates/items.tsx
hamza-client/src/modules/cart/templates/summary.tsx

- empty cart display added to checkout
- disabled check out button if cart empty

checkout  summary - empty cart display

---

hamza-client/src/modules/account/components/account-nav/index.tsx
hamza-client/src/modules/account/components/cancel-card/index.tsx
hamza-client/src/modules/account/components/order-overview/index.tsx
hamza-client/src/modules/account/components/processing-order-card/index.tsx
hamza-client/src/modules/account/components/refund-card/index.tsx
hamza-client/src/modules/account/components/shipped-card/index.tsx
hamza-client/src/modules/order/templates/cancelled.tsx
hamza-client/src/modules/order/templates/processing.tsx
hamza-client/src/modules/order/templates/refund.tsx
hamza-client/src/modules/order/templates/shipped.tsx
hamza-client/src/modules/tab-rendered/index.tsx
http-client/local-dev.http

- Processing Page
- Shipped Page
- Cancelled Page
- Refund Page

Order Pages

---

hamza-server/src/strategies/checkout-processors/basic-checkout.ts

Some old debug test code was the issue, artificially modifying the price.

Checkout price mismatch

---

hamza-client/src/modules/checkout/components/shipping/index.tsx
hamza-client/src/modules/collections/product_collection_filter/index.tsx
hamza-client/src/modules/common/components/cart-totals/index.tsx
hamza-client/src/modules/home/components/product-layout/index.tsx
hamza-client/src/modules/order/components/transaction-details/index.tsx
hamza-client/src/modules/products/components/product-card-group/index.tsx
hamza-client/src/modules/products/components/product-group-home/index.tsx
hamza-client/src/modules/products/components/product-group-store/index.tsx
hamza-client/src/modules/products/components/product-group-vendor/index.tsx
hamza-client/src/modules/products/components/product-preview/components/preview-checkout.tsx
hamza-client/src/modules/products/components/product-preview/price.tsx
hamza-client/src/modules/products/components/product-price/index.tsx
hamza-client/src/store/customer-auth/customer-auth.ts

Since I can't reproduce what seems to be a preferred currency mismatch, I've added logging to detect it.

logging for preferred currency mismatch

---

hamza-client/src/modules/order/components/shipping-details/index.tsx
hamza-server/src/api/custom/bucky/import/route.ts
hamza-server/src/services/buckydrop.ts

- changed function endsWith() to includes()
- possible issue with ssr and using the previous function

Fixed evm issue in orders

---

hamza-client/src/app/[countryCode]/(main)/account/@dashboard/profile/profile-form/profile-form.tsx

- Email now shows when verified

Show email profile

---

hamza-client/src/modules/cart/components/item-checkout/index.tsx
hamza-client/src/modules/cart/components/item/index.tsx
hamza-client/src/modules/cart/templates/items-checkout.tsx
hamza-client/src/modules/cart/templates/preview.tsx
hamza-client/src/modules/common/components/line-item-price/index.tsx

- fixed the bug where the currency showed 0 in final checkout
- possible timing issue that needs to be investigated

Price checkout bug - shenanigans #3

---

hamza-client/src/modules/home/components/product-layout/index.tsx
hamza-client/src/modules/products/components/product-actions/index.tsx
hamza-client/src/modules/products/components/product-card-group/index.tsx
hamza-client/src/modules/products/components/product-group-home/index.tsx
hamza-client/src/modules/products/components/product-group-store/index.tsx
hamza-client/src/modules/products/components/product-group-vendor/index.tsx
hamza-client/src/modules/products/components/product-preview/components/preview-checkout.tsx
hamza-server/src/services/buckydrop.ts

Fixed bug: sometimes there are no buckydrop variants, so we can't import the product. 
At the same time, frontend code is now more forgiving of products with no variants.

Bucky variant import fix

---

hamza-client/src/modules/order/components/items/index.tsx

removed review button from order details

removed review button from order details

---

hamza-server/src/services/product.ts

Exclude certain products from queries that display product grids/tables/lists on site: 
- no products without a store 
- no products where status != 'published'
- no products without any variants
This is to easily hide products when needed, and to avoid products that will cause issues.

exclude certain products from queries

---

hamza-client/next.config.js

Next.config - allow images from bucky

next.config changes for images

---

hamza-server/src/api/custom/bucky/import/route.ts
hamza-server/src/services/buckydrop.ts

Import single specific buckydrop products by product link

import products by link

---

currency-conversion/package.json
hamza-client/package.json
hamza-server/package.json

Modified package.json files with version numbers, project names

upped the version numbers

---

hamza-client/src/modules/cart/components/item-checkout/index.tsx
hamza-client/src/modules/cart/components/item/index.tsx
hamza-client/src/modules/cart/templates/preview.tsx
hamza-client/src/modules/checkout/templates/checkout-summary/index.tsx
hamza-client/src/modules/common/components/line-item-price/index.tsx
hamza-client/src/modules/common/components/line-item-unit-price/index.tsx
hamza-client/src/modules/order/components/item/index.tsx
hamza-client/src/store/customer-profile/customer-profile.ts
hamza-server/src/api/custom/customer/get-currency/route.ts
hamza-server/src/services/customer.ts

- created backend api to get customer currency code
- created fetch function to get currency code inside lineItemPrice
- removed unnecessary props
- updated lineItemPrice comp throughout app

Checkout Currency Shan #2 - Updated LineItemPrice

---

hamza-client/src/modules/common/components/line-item-price/index.tsx

- updated the api route to new end point

Updated  preferred currency api end point in LineItemPrice

---

hamza-client/package.json
hamza-client/src/lib/data/index.ts
hamza-server/src/api/custom/bucky/import/route.ts
hamza-server/src/api/custom/customer/route.ts
hamza-server/src/api/custom/store/products/route.ts
hamza-server/src/api/route-handler.ts

This is a fix or workaround for the bug in which customer data is seemingly cached on the server by medusa, allowing users to use unrelated users' accounts. And some related things.

Fix getCustomer bug

---

hamza-client/package.json
hamza-client/src/app/[countryCode]/(main)/account/@dashboard/addresses/page.tsx
hamza-client/src/app/[countryCode]/(main)/account/@dashboard/notifications/page.tsx
hamza-client/src/app/[countryCode]/(main)/account/@dashboard/page.tsx
hamza-client/src/app/[countryCode]/(main)/account/@dashboard/profile/page.tsx
hamza-client/src/app/[countryCode]/(main)/account/@dashboard/profile/profile-form/profile-form.tsx
hamza-client/src/app/[countryCode]/(main)/account/@dashboard/reviews/page.tsx
hamza-client/src/app/[countryCode]/(main)/account/@dashboard/verify/page.tsx
hamza-client/src/app/[countryCode]/(main)/account/layout.tsx
hamza-client/src/app/[countryCode]/(main)/cart/page.tsx
hamza-client/src/app/components/providers/rainbowkit/rainbow-provider.tsx
hamza-client/src/app/components/providers/rainbowkit/rainbowkit-utils/rainbow-utils.tsx
hamza-client/src/lib/data/index.ts
hamza-client/src/modules/cart/templates/preview.tsx
hamza-client/src/modules/checkout/templates/checkout-form/index.tsx
hamza-client/src/modules/common/components/line-item-price/index.tsx
hamza-server/src/api/custom/customer/route.ts
hamza-server/src/api/route-handler.ts

Ongoing bug fixes related to the medusa getCustomer bug

Get customer bug

---

hamza-client/src/modules/products/components/product-preview/components/preview-checkout.tsx

Product Details - Currency icon bug fix

---

hamza-client/src/app/components/providers/rainbowkit/rainbow-provider.tsx
hamza-server/src/api/route-handler.ts
hamza-server/src/migrations/2986572957694-AppLogs.ts
hamza-server/src/models/app-log.ts
hamza-server/src/repositories/app-log.ts
hamza-server/src/services/auth.ts
hamza-server/src/services/buckydrop.ts
hamza-server/src/services/cart.ts
hamza-server/src/services/confirmation-token.ts
hamza-server/src/services/crypto-payment-provider.ts
hamza-server/src/services/customer-notification.ts
hamza-server/src/services/customer.ts
hamza-server/src/services/discount.ts
hamza-server/src/services/notification-data-handler.ts
hamza-server/src/services/order.ts
hamza-server/src/services/payment-collection.ts
hamza-server/src/services/price-list.ts
hamza-server/src/services/product-collection.ts
hamza-server/src/services/product-review.ts
hamza-server/src/services/product-variant.ts
hamza-server/src/services/product.ts
hamza-server/src/services/smtp-notification-provider.ts
hamza-server/src/services/store.ts
hamza-server/src/services/whitelist.ts
hamza-server/src/services/wishlist.ts
hamza-server/src/strategies/cart-completion.ts
hamza-server/src/strategies/checkout-processors/basic-checkout.ts
hamza-server/src/strategies/price-selection.ts
hamza-server/src/utils/logging/logger.ts

New wrapper around Medusa logger which, while still using the internal medusa logger (conditionally), will also log to a database table. 
New env variables: 
LOG_TO_CONSOLE=1
LOG_TO_DATABASE=1 
Run setup/nuke database (new DB table, repository, and model for log entries)

Logging to Database

---

hamza-client/src/modules/order/templates/processing.tsx
hamza-server/package.json

- Order Processing - No longer shows blockchain email
- removed sudo in yarn "up" , now works on mac

Order Processing - No longer shows blockchain email

---

hamza-client/src/modules/cart/templates/items.tsx

- it was an overflow issue - fixed
- fixed mobile design

Cart Page - fixed scrollbars and mobile design

---

hamza-client/src/lib/data/index.ts
hamza-client/src/modules/checkout/actions.ts
hamza-client/src/modules/checkout/components/shipping/index.tsx
hamza-server/src/api/custom/cart/shipping/route.ts
hamza-server/src/services/cart.ts

Automatically choose the default shipping option & calculate shipping cost

Faster checkout

---

hamza-client/src/app/[countryCode]/(main)/verify-confirmation-token/[token]/page.tsx
hamza-client/src/app/[countryCode]/(main)/verify-email/page.tsx
hamza-client/src/lib/data/index.ts
hamza-client/src/modules/account/components/verify/index.tsx
http-client/local-dev.http

Broken routes

---

hamza-client/src/app/components/providers/rainbowkit/rainbow-provider.tsx

Crudest way to fix the issue. Fun fact, 23 & me has found that my dna is 96.8% neanderthal.

force reload after login

---

hamza-client/src/contracts.config.ts
hamza-client/src/modules/checkout/components/payment-button/payment-handlers.ts
hamza-client/src/modules/checkout/components/shipping/index.tsx
hamza-client/src/web3/abi/lite-switch-abi.ts
hamza-client/src/web3/index.ts

- Updated lite switch to emit the proper events with complete data 
- Updated the inputs for lite switch payments
- Updated the client accordingly
- Updated the lite switch address in config

Lite switch events

---

hamza-client/src/app/[countryCode]/(main)/verify-confirmation-token/[token]/page.tsx
hamza-client/src/modules/order/templates/processing.tsx

https://www.notion.so/hamza-market-token/What-s-with-all-the-Lines-Profile-Orders-8ebcb84ac2814e2bb6652af50a2d062e?pvs=4

FIX: weird lines in order page

---

hamza-server/src/api/route-handler.ts
hamza-server/src/services/auth.ts
hamza-server/src/services/buckydrop.ts
hamza-server/src/services/cart.ts
hamza-server/src/services/confirmation-token.ts
hamza-server/src/services/crypto-payment-provider.ts
hamza-server/src/services/customer-notification.ts
hamza-server/src/services/customer.ts
hamza-server/src/services/discount.ts
hamza-server/src/services/order.ts
hamza-server/src/services/payment-collection.ts
hamza-server/src/services/price-list.ts
hamza-server/src/services/product-collection.ts
hamza-server/src/services/product-review.ts
hamza-server/src/services/product-variant.ts
hamza-server/src/services/product.ts
hamza-server/src/services/smtp-notification-provider.ts
hamza-server/src/services/store.ts
hamza-server/src/services/whitelist.ts
hamza-server/src/services/wishlist.ts
hamza-server/src/strategies/checkout-processors/basic-checkout.ts
hamza-server/src/utils/logging/logger.ts

- Added (optional) prefixes to all log text, to make it easier to discern where things happened or where in the code to look for issues.

logger prefixes

---

hamza-server/package.json
hamza-server/src/currency-conversion/logger.ts
hamza-server/src/currency-conversion/rest-client.ts

winston logger.ts for currency-conversion/rest-client.ts

Winston Logger

---

hamza-client/src/app/[countryCode]/(main)/account/@dashboard/profile/page.tsx
hamza-client/src/app/components/wishlist/index.tsx
hamza-client/src/modules/account/components/wishlist/components/wishlist-card.tsx
hamza-client/src/modules/account/components/wishlist/index.tsx
hamza-server/src/api/custom/product/inventory/route.ts

- created api to get inventory by variant id
- add to cart disabled if no inventory
- created in stock badge on wishlist
- added product detail link to product thumbnail
- changed menu href to link to account/wishlist
- updated css and skeleton
- added default message if nothing in wishlist
Todo: In talks with Marc for minor desgin changes

Wishlist - api, logic and css update

---

hamza-client/src/modules/products/components/product-group-vendor/index.tsx
hamza-server/src/api/custom/category/products/route.ts

Fixed bug: 
Store page missing products in its main category 
Store id was being sent to api route; but store id was not present 
Made it send store name instead.

fixed bug: empty category on store page

---

hamza-client/src/modules/account/components/wishlist/index.tsx
hamza-server/src/buckydrop/bucky-client.ts
hamza-server/src/services/buckydrop.ts
hamza-server/src/services/product.ts

- Fix to wishlist client side, causing failure on staging
- Buckydrop method change (estimate shipping costs, params)

Wishlist fix

---

hamza-client/src/modules/checkout/components/shipping-address/index.tsx

a plumber gets paid for where he hits the pipe, I still can't find the pipe though

email required

---

hamza-server/src/api/custom/bucky/estimate/route.ts
hamza-server/src/api/custom/confirmation-token/verify/route.ts
hamza-server/src/currency-conversion/rest-client.ts
hamza-server/src/services/confirmation-token.ts

- tighter security in routes 
- cleanup 
- check first for existence of token & customer

tighter security & better handling for email verification

---

hamza-client/src/lib/util/get-client-cookies.ts

Forgot to check in a file from previous PR

forgot to check in a file from earlier PR

---

hamza-client/src/modules/home/components/search-and-filter-panel/components/filter-bar/FilterBar.tsx
hamza-client/src/modules/products/components/product-card-group/index.tsx

- filter bar toggleShowMore build error fix
- import error fix

Filter categories - build fix

---

hamza-server/src/services/product.ts

added product conversion for prod category query

Category price conversion

---

hamza-server/src/services/product.ts

When pulling products for category, ignore products which are not published & which aren't associated with any store.

Product category status

---

hamza-client/src/app/components/providers/rainbowkit/rainbow-provider.tsx
hamza-server/src/api/custom/cart/shipping/route.ts
hamza-server/src/api/custom/nonce/route.ts

- fixed login: broken by route-side refactoring 
- where returnStatus is called without a json payload, fixed to make it a json payload

Return status fix

---

hamza-client/src/app/components/providers/rainbowkit/rainbow-provider.tsx

Due to recent RainbowWrapper change

Fixed build error

---

hamza-client/src/app/components/wishlist-dropdown/index.tsx
hamza-client/src/modules/cart/components/empty-cart-message/index.tsx
hamza-client/src/modules/layout/components/cart-dropdown/index.tsx
hamza-client/src/modules/layout/components/cart-nav/components/cart-button.tsx
hamza-client/src/modules/products/templates/index.tsx
hamza-client/src/modules/search/templates/search-results-template/index.tsx

/store links now /shop in a bunch of places in client

/shop not /store in several places

---

hamza-client/src/modules/products/components/product-group-home/index.tsx
hamza-client/src/modules/products/components/product-group-vendor/index.tsx

- now shoes correct price of product

Store Page - Fixed product card pricing

---

hamza-client/src/app/[countryCode]/(main)/account/@dashboard/verify/page.tsx
hamza-client/src/app/[countryCode]/(main)/verify-email/page.tsx
hamza-client/src/modules/account/components/verify/index.tsx

- if user inputs verify toast error appears
- user can't submit without input

Email-Verify - cannot send if input empty

---

hamza-client/src/modules/home/components/search-and-filter-panel/components/filter-bar/FilterBar.tsx
hamza-client/src/modules/home/components/search-and-filter-panel/components/filter-bar/components/CategoryButtons.tsx
hamza-client/src/modules/products/components/product-group-home/index.tsx
hamza-client/src/modules/products/components/product-group-store/index.tsx
hamza-client/src/modules/shop/components/category-button.tsx
hamza-client/src/modules/shop/components/category-top-button.tsx
hamza-client/src/modules/shop/components/filter-bar-store.tsx
hamza-client/src/modules/shop/components/filter-tag.tsx
hamza-client/src/modules/shop/components/mobile-fitler/components/category-modal-button.tsx
hamza-client/src/modules/shop/components/mobile-fitler/components/filter-modal.tsx
hamza-client/src/modules/shop/components/store-side-menu.tsx
hamza-client/src/store/store-page/store-page.ts

- added skeletons for buttons
- added product categories for side panel and top filter
- updated filter tag icons
- refactored store side with latest api

Filter categories - Home and Store update

---

hamza-client/src/modules/products/components/product-group-store/index.tsx

fixed client build error

---

hamza-server/src/api/custom/order/customer-order/route.ts

https://www.notion.so/hamza-market-token/Orders-not-Displaying-26b57665faa0479a8ba5be86bf474a08?pvs=4

orders api fix

---

hamza-client/src/lib/data/index.ts
hamza-client/src/modules/account/components/account-nav/index.tsx
hamza-client/src/modules/account/components/order-overview/index.tsx
hamza-client/src/modules/order/components/empty-state/index.tsx
hamza-client/src/modules/order/templates/all.tsx
hamza-client/src/modules/order/templates/cancelled.tsx
hamza-client/src/modules/order/templates/delivered.tsx
hamza-client/src/modules/order/templates/processing.tsx
hamza-client/src/modules/order/templates/refund.tsx
hamza-client/src/modules/order/templates/shipped.tsx
hamza-server/src/api/custom/order/customer-orders/route.ts
hamza-server/src/api/custom/order/order-summary/route.ts
hamza-server/src/api/route-handler.ts
http-client/local-dev.http

https://www.notion.so/hamza-market-token/Empty-Orders-Page-2c3b1cbfb3ca44989a437eec40df9d32?pvs=4
Cleanup for showing empty page

Order display bug

---

currency-conversion/package.json
hamza-client/package.json
hamza-server/package.json
sql-scripts/0.3.0.sql

- upped the version numbers 
- added SQL scripts

version numbers and SQL scripts

---

hamza-client/src/app/[countryCode]/(main)/shop/[slug]/page.tsx
hamza-client/src/lib/data/index.ts
hamza-client/src/modules/account/components/shipped-card/index.tsx
hamza-client/src/modules/collections/product_collection_filter/index.tsx
hamza-client/src/modules/home/components/products/index.tsx
hamza-client/src/modules/home/components/search-and-filter-panel/data/data.ts
hamza-client/src/modules/products/components/product-group-vendor/index.tsx
hamza-client/src/modules/store/components/products/store-cat-button.tsx
hamza-client/src/modules/store/components/products/store-search.tsx

Changed names of some (not all) things from vendor to store for consistency of terminology with the backend & DB

changed vendor to store in many places

---

hamza-client/src/modules/products/components/product-group-vendor/index.tsx
hamza-client/src/modules/store/components/products/store-cat-button.tsx
hamza-client/src/modules/store/components/products/store-search.tsx
hamza-server/src/api/custom/store/products/category-name/route.ts
hamza-server/src/api/custom/store/products/handle/route.ts
hamza-server/src/services/product.ts

- created getStoreProductsByCategory() function in product.ts
- added documentation
- updated front end code to show all products and products by category
- updated API end point

Store Page - categories now show products

---

hamza-server/src/services/product.ts

Since updating existing products (during bulk import) isn't working, just optionally delete them and re-add them

delete existing product (optionally) when bulk importing

---

hamza-client/src/modules/checkout/components/payment-button/payment-handlers.ts
hamza-client/src/modules/home/components/search-and-filter-panel/data/data.ts
hamza-server/src/services/product.ts

This is needed for testing live; option to set price actually charged to 1 satoshi
Removed a hard-coded ALT_SEED option that is no longer needed

One satoshi discount

---

hamza-server/src/services/product.ts
sql-scripts/0.3.0.sql

Updated SQL script with category icons

Sql script update

---

hamza-client/src/modules/products/components/product-group-vendor/index.tsx
hamza-server/src/services/product.ts

- put  condition in getStoreProductsByCategory() to call getProductsFromStoreWithPrices() if categoryName = "all"

Store Page - no longer shows duplicate products in store

---

hamza-client/src/modules/layout/templates/nav-4/menu/account-menu.tsx

Instead of "Profile" and "Settings" in the pulldown menu, now we just have "Manage my Account"

manage my account to replace 'settings'

---

hamza-server/src/api/admin/custom/payments/verify/route.ts
hamza-server/src/services/buckydrop.ts
hamza-server/src/services/order.ts
hamza-server/src/services/payment-verification.ts
hamza-server/src/web3/index.ts

- check first that bucky order is ready before trying to reconcile its status
- improvements to on-chain payment verification 
- fixed bug: variant metadata saved as string
- handle failed buckydrop order creation

Buckydrop order proc bugs

---

hamza-client/src/modules/home/components/search-and-filter-panel/components/filter-bar/components/CategoryButtons.tsx
hamza-client/src/modules/products/components/product-group-home/index.tsx
hamza-client/src/modules/products/components/product-group-store/index.tsx
hamza-client/src/modules/shop/components/filter-tag.tsx
hamza-server/src/api/custom/product/category/products/route.ts
hamza-server/src/api/custom/store/products/route.ts
hamza-server/src/services/product.ts

- All category selection causing crash (bad query on backend)
- Other categories selection returning no products

Fix shop page

---

hamza-client/src/modules/products/components/product-group-home/index.tsx
hamza-client/src/modules/products/components/product-group-store/index.tsx
hamza-server/src/api/custom/product/category/products/route.ts
hamza-server/src/api/custom/product/filter/route.ts
hamza-server/src/api/custom/store/products/route.ts
hamza-server/src/api/route-handler.ts
hamza-server/src/services/product.ts

Applied filter for duplicate products (products in multiple categories)

Duplicate products fix

---

hamza-server/src/services/buckydrop.ts
hamza-server/src/services/cart.ts

- Fixes the issue of some buckydrop -imported products having way-too-high prices in ETH only

Bug fix: Wrong cny-eth conversions

---

hamza-server/src/api/custom/bucky/import/route.ts
hamza-server/src/services/buckydrop.ts

Buckydrop has product images for variants as well; those are now also imported and associated with variants.

Product variant images import from Buckydrop

---

hamza-client/src/modules/home/components/search-and-filter-panel/components/filter-bar/components/CategoryButtons.tsx
hamza-client/src/modules/home/components/search-and-filter-panel/components/filter-bar/components/FilterModal.tsx
hamza-server/src/services/product.ts
hamza-server/src/utils/price-conversion/index.ts
sql-scripts/0.3.0.sql
sql-scripts/0.4.0.sql

Hotfix for some issues plaguing alpha on most recent deployment. 
- broken category image 
- missing cat image crashing homepage 
- price filtering breaking on products with no variants

0.4.0 hotfix

---

hamza-server/src/api/custom/product/filter/route.ts

Had to disable price filter for now, as it's causing some products to not show up. I can explain more in person.

disabled price filter

---

hamza-client/src/lib/data/index.ts
hamza-client/src/modules/checkout/actions.ts
hamza-client/src/modules/common/components/cart-totals/index.tsx
hamza-server/src/api/custom/cart/email/route.ts
hamza-server/src/migrations/1764855573305-CartEmail.ts
hamza-server/src/models/cart-email.ts
hamza-server/src/repositories/cart-email.ts
hamza-server/src/services/cart-email.ts
hamza-server/src/services/cart.ts

Workaround: a new table to relate cart to its true email address. 
GetCart is updated to set the cart's email to the true email address (from the new table)

Cart email workaround

---

hamza-client/src/modules/products/components/option-select/index.tsx
hamza-client/src/modules/products/components/product-preview/components/preview-checkout.tsx
hamza-client/src/modules/products/components/product-preview/components/preview-gallery.tsx
hamza-client/src/modules/products/templates/index.tsx

- Improve Display 
- Display Variant Price on Variant Selection
- Default Variant Selected
- Make sure Correct Variant Purchased (needs further testing) 
- Display Variant Image on Variant Selection (needs further testing this feels janky atm)

Product Variant handling

---

hamza-server/src/loaders/secrets-manager.ts

Fixed an issue causing secrets from AWS Secrets Manager to be not read into process.env

Secrets manager fix

---

hamza-client/src/modules/shop/components/filter-carousel/category-top-button.tsx
hamza-server/src/services/product.ts

- updated function "getFilteredProductsByCategory",  for custom/category/filter
- all button resets zustand states

Duplicate Products Fix + All button resets states

---

hamza-server/src/currency.config.ts
hamza-server/src/services/payment-verification.ts
hamza-server/src/web3/contracts/lite-switch.ts
hamza-server/src/web3/index.ts

- get RPC url from .env
- get starting block number from .env
- account for decimal points when verifying amount 
- cleanup

Payment verify fixes

---

hamza-client/src/modules/checkout/components/shipping-address/index.tsx

- added input to form
- updates with save address
- saves to db

Address line 2 

---

hamza-client/src/modules/layout/templates/nav-4/connect-button/index.tsx
hamza-client/src/modules/layout/templates/nav-4/index.tsx
hamza-client/src/modules/layout/templates/nav-4/menu/account-menu.tsx

- wallet button now is visible while loading
- fix margins on settings menu such that search bar is now 100% width
- fixed margin bottom of verify account link on profile menu

Nav cleanup

---

hamza-client/src/modules/cart/templates/items.tsx

- removed overflow and scrollable
- component expands with cart

fixed scroll issue

---

hamza-client/src/modules/account/components/processing-order-card/index.tsx
hamza-client/src/modules/checkout/actions.ts
hamza-client/src/modules/checkout/components/addresses/index.tsx
hamza-client/src/modules/checkout/components/shipping-address/index.tsx

- order status now shows address 2
- correct address shows after continue to delivery
- updated state to correct include formdata for address 2

Order Status Card + Address updating propery

---

hamza-client/src/modules/products/components/product-group-vendor/index.tsx
hamza-client/src/modules/store/components/products/store-cat-button.tsx
hamza-client/src/modules/store/components/products/store-search.tsx
hamza-client/src/store/store-page/vendor.ts
hamza-server/src/api/custom/store/products/category-name/route.ts
hamza-server/src/services/product.ts

- updated route and service
- products now multi cat
- cleaned up front-end

Store Page - API and Service Update, Multi-Cat

---

hamza-client/src/modules/common/components/line-item-price/index.tsx

`${process.env.NEXT_PUBLIC_MEDUSA_BACKEND_URL}/custom/customer/preferred-currency`,

localhost:9000 changed to env var NEXT_PUBLIC_MEDUSA_BACKEND_URL

---

hamza-client/src/modules/checkout/components/payment-button/index.tsx

- Updated the message for doWalletPayment failing
- Added finally clause to completeCheckout to set submitting to false

Payment-button: Removed dupe toast messages, added finally clause to completeCheckout()

---

hamza-server/src/services/product.ts

- updated getAllStoreProductByCategory to filter out unpublished products

Store Page - Hide unpublished products

---

hamza-client/src/app/[countryCode]/(main)/verify-confirmation-token/[token]/page.tsx
hamza-server/src/api/custom/confirmation-token/generate/route.ts

Simple bugs causing email confirmation not to work

Fix for email confirmation page

---

hamza-server/src/services/product.ts
hamza-server/src/utils/cache/seamless-cache.ts

Using SeamlessCache (TM), cached the query that loads the category buttons.

Cache category buttons query

---

hamza-client/src/modules/checkout/components/shipping/index.tsx

If no shipping method selected, select the default & move next

shipping bug: set default shipping method if none selected

---

hamza-client/src/app/[countryCode]/(main)/store/[slug]/page.tsx
hamza-client/src/modules/order/templates/processing.tsx

- Commented out follow seller
- Centering the other button so it doesn't look weird

Follow seller

---

hamza-client/src/modules/cart/components/item/index.tsx

- looks good on mobile now
- created padding between quantity and delete button from title name
- added larger gap between delete button and quantity on mobile
- increased mobile thumbnail size

Cart Checkout Design - Fixed mobile and desktop product card

---

hamza-client/src/modules/checkout/components/payment-button/payment-handlers.ts

- check wallet balance before payment
- give error 'insufficient balance' before attempt to pay 
- changed payment button to "Place Order" from "Place Order: Crypto" 
- error under payment button clears when button clicked

Check wallet balance before payment

---

hamza-client/next.config.js
hamza-client/src/modules/home/components/search-and-filter-panel/components/filter-bar/FilterBar.tsx
hamza-client/src/modules/shop/components/filter-carousel/filter-bar-store.tsx
hamza-server/data/seed.json
hamza-server/src/api/admin/custom/user/route.ts
hamza-server/src/api/custom/bucky/setup/route.ts
hamza-server/views/order-placed.ejs
hamza-server/views/verify-confirmation.ejs
hamza-server/views/verify-email.ejs
sql-scripts/0.3.0.sql

Changes images.hamza.biz to images.hamza.market

Images hamza market

---

hamza-client/src/modules/home/components/search-and-filter-panel/components/filter-bar/FilterBar.tsx
hamza-client/src/modules/home/components/search-and-filter-panel/components/filter-bar/components/CategoryButtons.tsx
hamza-client/src/modules/store/components/products/store-cat-button.tsx

- added button minwidth
- adjusted button horizontal padding

Store Page - Cat button overflowing text /  clean up home page filter with dupes

---

hamza-server/src/utils/price-conversion/index.ts

This should stop the DB from being spammed when exchange rates are being cached for the first time.

added a mutex to keep the db from being spammed

---

hamza-client/src/modules/account/components/wishlist/components/wishlist-card.tsx
hamza-client/src/modules/account/components/wishlist/index.tsx
hamza-client/src/modules/home/components/search-and-filter-panel/components/filter-bar/FilterBar.tsx
hamza-client/src/store/wishlist/mutations/wishlist-mutations.tsx
hamza-client/src/store/wishlist/wishlist-store.tsx
hamza-server/src/api/custom/wishlist/item/route.ts
hamza-server/src/migrations/1713505343211-Wishlist.ts
hamza-server/src/models/wishlist-item.ts
hamza-server/src/services/wishlist.ts
http-client/local-dev.http

- Wishlist now relates to variant id instead of product id 
- Wishlist bug (the weird inability to load thing) has been fixed by Garo

Wishlist variant

---

hamza-server/src/services/confirmation-token.ts

- Randomize confirmation token when generated

randomize conf. token

---

hamza-server/src/api/custom/google/route.ts
hamza-server/src/api/route-handler.ts

Error handling on the server side for google auth had some holes; fixed now.

Oauth (google) cleanup level 1: handling errors on server side

---

hamza-client/src/app/[countryCode]/(main)/account/@dashboard/verify/page.tsx
hamza-client/src/modules/account/components/verify/index.tsx
hamza-server/package.json

- updated designs
- updated validation
- updated toast giving wrong message

Verify page - updated designs and validation

---

hamza-client/src/app/[countryCode]/(main)/categories/[...category]/page.tsx
hamza-client/src/app/[countryCode]/(main)/collections/[handle]/page.tsx
hamza-client/src/lib/data/index.ts
hamza-client/src/modules/account/components/delivered-card/index.tsx
hamza-client/src/modules/account/components/wishlist/components/wishlist-card.tsx
hamza-client/src/modules/cart/actions.ts
hamza-client/src/modules/home/components/product-layout/components/product-card.tsx
hamza-client/src/modules/products/components/product-actions/index.tsx
hamza-client/src/modules/products/components/product-preview/components/preview-checkout.tsx
hamza-client/src/modules/products/components/product-preview/components/product-info.tsx
hamza-server/src/services/cart.ts
hamza-server/src/strategies/price-selection.ts

Handles the last now price shenanigan on the product details page.

Default price bug

---

hamza-server/src/services/cart.ts
hamza-server/src/strategies/price-selection.ts

Adjust prices of line items in cart when retrieving cart; convert from store currency to user preferred currency.

convert cart item currencies in cart

---

hamza-server/src/services/product.ts

- easy fix, was missing a repository (categoryCache.retrieve) because one had not been passed in to it

pass value to categoryCache.retrieve

---

hamza-server/src/services/buckydrop.ts

Buckydrop manual shipping calculation

---

hamza-client/src/app/components/providers/rainbowkit/rainbow-provider.tsx
hamza-client/src/lib/data/index.ts
hamza-server/src/api/custom/cart/email/route.ts
hamza-server/src/api/custom/cart/recover/route.ts
hamza-server/src/services/cart.ts
http-client/local-dev.http

When a user logs back in after being logged out, it recovers their most recent cart if it's not yet completed
- API route /custom/cart/recover 
- CartService method recover
- SSR api call on client: recoverCart
- added code to rainbow client-side login routine

Cart recovery

---

hamza-client/src/lib/util/get-product-price.ts
hamza-client/src/modules/account/components/wishlist/components/wishlist-card.tsx
hamza-client/src/modules/account/components/wishlist/index.tsx
hamza-server/src/api/custom/wishlist/route.ts
hamza-server/src/services/product.ts
hamza-server/src/services/wishlist.ts
http-client/local-dev.http

Wishlist bug fixes: 
- Icon now showing, 
- Loading currencies from server side working
- Broken: Swapping currencies client side still broken

Wishlist bugs

---

hamza-client/src/modules/layout/templates/nav-4/menu/account-menu.tsx

arrive at account/profile

---

hamza-client/src/modules/account/components/notification-toggle/toggles.tsx
hamza-server/src/api/custom/bucky/verify/route.ts
hamza-server/src/api/custom/customer/notification/route.ts
hamza-server/src/services/customer-notification.ts
hamza-server/src/services/customer.ts

Cleaned up notifications: 
- default notification types are applied when user created 
- cleaned up code a little bit 
- commented out (on notifications page) options that we don't offer right now
- renamed a few things

Notifications cleanup

---

hamza-server/src/services/cart.ts
hamza-server/src/services/customer-notification.ts
hamza-server/src/services/order.ts
hamza-server/src/services/smtp-notification-provider.ts
hamza-server/src/strategies/checkout-processors/basic-checkout.ts

- conditionally sending the order.placed email based on customer notifications choices.

Check notifications

---

hamza-client/src/app/components/providers/rainbowkit/rainbow-provider.tsx
hamza-client/src/lib/data/index.ts
hamza-server/src/api/custom/verify/route.ts

To avoid logging in to another user's account. 
1. disable caching on all axios calls
2. doublecheck that outgoing wallet address (wallet address on client) matches the one coming back from the server
3. use axios instead of fetch for nonce call

Login double checks

---

hamza-client/src/app/[countryCode]/(main)/error.tsx
hamza-client/src/app/[countryCode]/(main)/store/[slug]/page.tsx
hamza-server/src/api/custom/store/categories/route.ts

If you go to the /store page with a store name of a store that doesn't exist, you get redirected to 404 page.

404 for missing store

---

hamza-client/src/modules/account/components/review-page/index.tsx
hamza-server/src/services/product-review.ts
http-client/local-dev.http

Bug Fixes: 
- Fixed listing all order items for multi order on client end
- Fixed Non reviewed filtering in product-review service
- Added thumbnail to pending && archived reviews

Review hotfixes

---

hamza-client/next.config.js
hamza-client/src/lib/data/index.ts

added new image domain in next.config

---

hamza-client/src/app/[countryCode]/(main)/verify-confirmation-token/[token]/page.tsx
hamza-client/src/modules/account/components/verify/index.tsx

- success page update
- validation update and input now forces lower case input

Email Verification Update

---

hamza-client/src/modules/products/components/product-preview/components/quantity-button.tsx

my="1rem", the spacing was just not equal between variant and quantity button

spacing fix

---

hamza-client/src/app/[countryCode]/(main)/account/@dashboard/orders/page.tsx
hamza-client/src/app/[countryCode]/(main)/account/@dashboard/profile/page.tsx
hamza-client/src/app/[countryCode]/(main)/account/@dashboard/profile/profile-form/profile-form.tsx
hamza-client/src/lib/data/index.ts
hamza-client/src/modules/account/components/order-overview/index.tsx
hamza-client/src/modules/order/templates/all.tsx
hamza-server/src/api/custom/order/customer-orders/route.ts
hamza-server/src/services/order.ts
http-client/local-dev.http

Whoever merges this should please test it in production before doing so, it is working on my end... I hope its working, trust but verify. 
- Blank page: Orders (fixed)
- Firstname/Lastname disappear (fixed)

Profile usequery

---

hamza-client/src/lib/data/index.ts
hamza-client/src/modules/account/components/verify/index.tsx
hamza-server/src/api/custom/confirmation-token/generate/route.ts
hamza-server/src/api/route-handler.ts
hamza-server/src/services/confirmation-token.ts

- if email already in use return error
- updated axioscall function with john..to be continued

Verify Page - Email verify confirmation

---

hamza-client/src/modules/account/components/wishlist/components/wishlist-card.tsx

Wishlist mobile

---

hamza-client/src/modules/order/templates/processing.tsx

hiding history panel for processing tab in account/orders

hide history panel

---

hamza-client/src/app/[countryCode]/(main)/account/@dashboard/notifications/page.tsx
hamza-client/src/app/[countryCode]/(main)/account/@dashboard/reviews/page.tsx
hamza-client/src/app/error.tsx
hamza-client/src/lib/exceptions.ts

- Fixed Error page buttons
- Added Verification Error checking for; 1. Reviews Page 2. Notifications Page

Error pages

---

hamza-client/src/app/[countryCode]/(main)/account/@dashboard/reviews/page.tsx
hamza-client/src/modules/account/components/reviews/index.tsx
hamza-client/src/modules/editreview/[id]/edit-review-template.tsx
hamza-client/src/modules/review/[id]/review-template.tsx

Fixed mobile responsiveness for reviews page in accounts/reviews..

Review mobile

---

hamza-client/src/app/[countryCode]/(main)/account/@dashboard/page.tsx
hamza-client/src/app/[countryCode]/(main)/account/layout.tsx
hamza-client/src/app/error.tsx
hamza-client/src/modules/account/components/account-nav/index.tsx
hamza-client/src/modules/products/components/product-preview/components/store-banner.tsx

**READ BEFORE MERGING**
AccountPageLayout.tsx now has a hardstop; 
- IF no customer, we will get the shakespear page
- IF connected, and not verified;
- non-verified tabs show 
-  verification requiring pages will show with EXPECTED error
- IF Connected, shows all tabs
- This has been tested in production build, these bugs are very annoying to spot though. **PR's like this should be actually reviewed before merging.**

Account refactor

---

hamza-server/src/api/custom/verify/route.ts

name randomizer

---

hamza-server/src/services/buckydrop.ts

Bug in calculation of shipping price (Buckydrop)

Fixed bug causing shipping price to be zero

---

hamza-client/src/modules/common/components/cart-totals/index.tsx

Fixed bug that causes cart total & subtotal to be invisible or 0.00

Fixed discrepancy between cart currency and preferred currency

---

hamza-client/src/app/[countryCode]/(main)/account/@dashboard/profile/profile-form/components/profile-image.tsx
hamza-client/src/app/[countryCode]/(main)/account/@dashboard/profile/profile-form/profile-form.tsx
hamza-client/src/app/components/providers/rainbowkit/rainbow-provider.tsx
hamza-client/src/modules/layout/templates/nav/menu-desktop/account-menu.tsx
hamza-client/src/modules/layout/templates/nav/menu-mobile/menu/mobile-account-menu.tsx

Dynamic avatars for customers from dicebear

Avatar generator

---

hamza-client/src/app/components/providers/rainbowkit/rainbow-provider.tsx

Fixed a problem introduced in earlier PR, preventing login in some cases.

fixed problem in client wallet check

---

hamza-client/src/modules/account/components/account-nav/account-nav-desktop/account-nav-desktop.tsx
hamza-client/src/modules/account/components/account-nav/account-nav-mobile/account-nav-mobile.tsx
hamza-client/src/modules/account/components/account-nav/components/nav-link-mobile.tsx
hamza-client/src/modules/account/components/account-nav/components/nav-link.tsx

- added logout to mobile
- updated verify and orders icon
- updated alignment of icons and title to be more even
- improved desktop look

Account Nav - Desktop and mobile update

---

hamza-client/src/modules/account/components/reviews/index.tsx

Refactor; 
-  fetchPendingReviews and fetchReviews  replaced with useQuery hooks. 
- Eliminate the need for manual state management, like useEffect for triggering data fetches and useState for managing loading/error states
- improved loading and error handling
- automatic caching
- simplified code structure

Replacing manual data fetching with useQuery for reviews

---

hamza-client/src/app/[countryCode]/(main)/account/@dashboard/reviews/page.tsx
hamza-client/src/app/error.tsx
hamza-client/src/modules/order/templates/all.tsx
hamza-client/src/modules/order/templates/processing.tsx

Refactored Order Processing Tab; 
- Removed the need for zustand
- Automatically refetching using tanstack 
- useQuery to fetch orders 
- useMutations to handle order cancellation and invalidations 
- Edge case handling

processing page refactor

---

hamza-client/src/modules/account/components/account-nav/account-nav-desktop/account-nav-desktop.tsx
hamza-client/src/modules/account/components/account-nav/account-nav-mobile/account-nav-mobile.tsx
hamza-client/src/modules/account/components/account-nav/components/nav-link-desktop-orders.tsx
hamza-client/src/modules/account/components/account-nav/components/nav-link-mobile-orders.tsx
hamza-client/src/modules/account/components/account-nav/components/nav-link-mobile.tsx
hamza-client/src/modules/account/components/account-nav/components/nav-link.tsx

- created ordertablinks for mobile and desktop
- orders tabs now work on mobile
- updated design and components

Account menu - desktop & mobile

---

hamza-client/src/lib/data/index.ts
hamza-client/src/modules/account/components/cancel-card/index.tsx
hamza-client/src/modules/order/templates/cancelled.tsx
hamza-client/src/modules/order/templates/processing.tsx
hamza-server/src/api/custom/order/cancel/route.ts
hamza-server/src/services/order.ts
http-client/local-dev.http

Feature update; 
- Server Side
- Saving Cancel Reason: String
- Saving Cancel Reason: Date() 
- Client Side
- Refactor Processing mutation to accept cancel_reason state
- Cancelled Card Prop drilled metadata cancel_reason && cancel_date

Cancel reason

---

hamza-client/src/modules/account/components/cancel-card/index.tsx
hamza-client/src/modules/order/templates/cancelled.tsx

Refactoring;
- Remove state / useEffects in canceled template and used spinner / loading
- Removed useEffect && states in CancelCard, replaced with useQuery caching / spinner to load data

refactoring Canceled Page

---

hamza-client/src/modules/account/components/delivered-card/index.tsx
hamza-client/src/modules/order/templates/delivered.tsx

Same as other pages
Refactoring;
Remove state / useEffects in Delivered template and used spinner / loading
Removed useEffect && states in Delivered Card, replaced with useQuery caching / spinner to load data
This one could use an upgrade with modifying the `buy again` to a mutation (added a TODO)

Delivered page refactor

---

hamza-client/src/modules/account/components/refund-card/index.tsx
hamza-client/src/modules/order/templates/processing.tsx
hamza-client/src/modules/order/templates/refund.tsx

Same as other pages
Refactoring;
Remove state / useEffects in refund template and used spinner / loading
Removed useEffect && states in refundCard, replaced with useQuery caching / spinner to load data

refund page refactor

---

hamza-server/scripts/call-api.js
hamza-server/scripts/import-bucky.js
hamza-server/scripts/process-bucky.js
hamza-server/scripts/track-bucky.js
hamza-server/src/api/admin/custom/bucky/estimate/route.ts
hamza-server/src/api/admin/custom/bucky/import/route.ts
hamza-server/src/api/admin/custom/bucky/orders/route.ts
hamza-server/src/api/admin/custom/bucky/setup/route.ts
hamza-server/src/api/admin/custom/bucky/track/route.ts
hamza-server/src/api/admin/custom/bucky/verify/route.ts

Moved bucky routes to admin
Created scripts to call bucky routes in admin

Bucky lockdown

---

hamza-client/src/app/[countryCode]/(main)/cart/loading.tsx
hamza-client/src/app/[countryCode]/(main)/cart/page.tsx
hamza-client/src/app/components/providers/rainbowkit/connect-button/connect-button.tsx
hamza-client/src/app/components/providers/rainbowkit/rainbow-provider.tsx
hamza-client/src/modules/layout/templates/nav/menu-desktop/connect-wallet/index.tsx
hamza-client/src/modules/skeletons/components/skeleton-order-summary/index.tsx
hamza-client/src/modules/skeletons/templates/skeleton-cart-page/index.tsx
hamza-client/src/store/customer-auth/customer-auth.ts

Cart page  -  skeleton

---

hamza-client/src/modules/account/components/shipped-card/index.tsx
hamza-client/src/modules/order/templates/shipped.tsx

Same as other pages
Refactoring;
Remove state / useEffects in Shipped template and used spinner / loading
Removed useEffect && states in Shipped Card, replaced with useQuery caching / spinner to load data

Shipped Page Refactor

---

hamza-client/src/modules/products/components/product-preview/components/terms-of-service/product-details-tos.tsx

- updated mobile design for TOS

updated TOS mobile

---

hamza-client/src/app/[countryCode]/(main)/account/@dashboard/profile/profile-form/components/profile-image.tsx
hamza-client/src/modules/layout/templates/nav/menu-desktop/account-menu.tsx
hamza-client/src/modules/layout/templates/nav/menu-mobile/menu/mobile-account-menu.tsx
hamza-server/src/api/custom/verify/route.ts
hamza-server/src/api/route-handler.ts

Fix for issue: inability to create customer record causes confusion (is not a clear failure)

Login bug fix

---

hamza-client/src/modules/account/components/cancel-card/index.tsx
hamza-client/src/modules/account/components/delivered-card/index.tsx
hamza-client/src/modules/account/components/refund-card/index.tsx
hamza-client/src/modules/account/components/shipped-card/index.tsx
hamza-client/src/modules/order/templates/all.tsx
hamza-client/src/modules/order/templates/cancelled.tsx
hamza-client/src/modules/order/templates/delivered.tsx
hamza-client/src/modules/order/templates/processing.tsx
hamza-client/src/modules/order/templates/refund.tsx
hamza-client/src/modules/order/templates/shipped.tsx

Chain Querying and Debouncing Order History...

Order hotfixes

---

hamza-client/src/app/components/providers/rainbowkit/rainbow-provider.tsx

At login, compare the wallet address recognized on the server with the one recognized on the client, by Rainbow / Wagmi itself. If they don't match, login won't happen.

compare wallet address on login

---

hamza-server/views/order-placed.ejs
hamza-server/views/verify-confirmation.ejs
hamza-server/views/verify-email.ejs

Updated email templates with new text & opt-out links

Email templates

---

hamza-client/src/store/wishlist/wishlist-store.tsx
hamza-server/src/services/order.ts

Display orders in order of date created DESC
Changed on the server side

Display orders in order of date created DESC

---

hamza-client/src/store/wishlist/wishlist-store.tsx

Check for wishlist items before accessing

Check for wishlist items before accessing

---

hamza-client/src/app/[countryCode]/(main)/layout.tsx
hamza-client/src/modules/account/components/account-nav/account-nav-desktop/account-nav-desktop.tsx
hamza-client/src/modules/layout/templates/nav/index.tsx
hamza-client/src/modules/products/components/product-preview/components/product-info/product-info.tsx
hamza-client/src/modules/products/components/product-preview/components/summary/preview-checkout.tsx
hamza-client/src/modules/products/components/product-preview/components/terms-of-service/policies/payment-policy.tsx
hamza-client/src/modules/products/components/product-preview/components/terms-of-service/policies/return-policy.tsx
hamza-client/src/modules/products/components/product-preview/components/terms-of-service/policies/shipping-policy.tsx
hamza-client/src/modules/products/components/product-preview/components/terms-of-service/product-details-tos.tsx
hamza-client/src/modules/products/templates/index.tsx

- various mobile configurations
- removed navbar from mobile
- updated modal TOS for mobile

Product Details - mobile update

---

currency-conversion/src/coin-gecko.controller.ts
hamza-client/src/app/[countryCode]/(main)/health/page.tsx
hamza-server/src/api/custom/health/route.ts
hamza-server/src/api/custom/meilisearch/route.ts

Added health check routes to those that need them.

Health checks

---

hamza-server/src/api/custom/twitter/route.ts

- Fixed issues in twitter oauth handling route 
- Standardized to use RouteHandler like the other Oauth handlers 
- Added decoded jwt medusa token 
- Added call to CustomerRepo to update user

Twitter oauth fix

---

hamza-client/package.json
hamza-client/src/app/components/providers/rainbowkit/rainbow-provider.tsx
hamza-client/src/lib/data/index.ts
hamza-client/src/modules/account/components/reviews/index.tsx
hamza-client/src/modules/order/templates/cancelled.tsx
hamza-client/src/modules/order/templates/delivered.tsx
hamza-client/src/modules/order/templates/refund.tsx
hamza-client/src/modules/order/templates/shipped.tsx
package.json

- Review Page fixes
- If Order panel empty, skip it..

Review Page fixes

---

hamza-client/src/app/[countryCode]/(main)/account/@dashboard/profile/profile-form/profile-form.tsx

- empty first name and last name fields return toast
- fixed the width of currency field if email exists

Profile - empty first name and last name fields return toast

---

hamza-client/src/app/[countryCode]/(main)/error/client-error-simulator.tsx
hamza-client/src/app/[countryCode]/(main)/error/page.tsx
hamza-client/src/app/[countryCode]/(main)/settings/page.tsx
hamza-client/src/app/error.tsx
hamza-client/src/app/global-error.tsx

Can't generate; 
Application error: a server-side exception has occured
Application error: a client-side exception has occured
/settings  -> simulates server side error
/error -> simulates client side error

Error simulator

---

hamza-client/src/modules/account/components/wishlist/components/wishlist-card.tsx

not sure if this works, its a shot in the dark..

reset wishlist

---

hamza-client/src/modules/checkout/components/shipping/index.tsx
hamza-client/src/modules/products/components/product-group-home/component/home-product-card.tsx
hamza-client/src/modules/products/components/product-group-home/index.tsx
hamza-client/src/modules/products/components/product-group-shop/index.tsx
hamza-client/src/modules/products/components/product-group-store/index.tsx
hamza-client/src/modules/products/components/product-preview/components/product-info/product-info.tsx
hamza-client/src/modules/shop/components/product-card.tsx
hamza-server/src/api/custom/cart/shipping/route.ts

The product cards and product info page now show the correct ratings.

Products Reviews - Reviews hardcoded

---

hamza-client/src/modules/home/components/product-layout/index.tsx
hamza-client/src/modules/products/components/product-card-group/index.tsx
hamza-client/src/modules/products/components/product-group-home/index.tsx
hamza-client/src/modules/products/components/product-group-shop/index.tsx
hamza-client/src/modules/products/components/product-group-store/index.tsx

When getting avg. rating, just a cautious check for zero before dividing

Dheck for zero before dividing

---

hamza-server/scripts/import-bucky.js
hamza-server/scripts/process-bucky.js
hamza-server/scripts/track-bucky.js
hamza-server/src/api/admin/custom/bucky/process/route.ts
hamza-server/src/services/payment-verification.ts

- Updates to utility scripts that call admin routes
- Added new admin route to process bucky orders without verifying them first (mainly for test orders and special cases)

Script fixes

---

hamza-client/src/app/[countryCode]/(main)/account/@login/page.tsx
hamza-client/src/lib/data/index.ts
hamza-client/src/modules/products/components/product-preview/components/product-info/product-info.tsx
hamza-server/src/buckydrop/bucky-client.ts
hamza-server/src/services/order.ts
hamza-server/src/services/product-collection.ts
hamza-server/src/services/product-review.ts
hamza-server/src/services/product.ts
hamza-server/src/services/role.ts
hamza-server/src/services/store.ts
hamza-server/src/services/whitelist.ts
hamza-server/src/strategies/checkout-processors/basic-checkout.ts

Removed redundant awaits from many methods.

Removed redundant awaits

---

hamza-client/src/modules/products/components/product-group-home/component/home-product-card.tsx
hamza-client/src/modules/products/components/product-group-home/index.tsx
hamza-client/src/modules/products/components/product-preview/components/product-info/product-info.tsx
hamza-client/src/modules/shop/components/product-card.tsx
hamza-client/src/store/product-preview/product-preview.ts

- fixed lagging rating in product info page
- fixed default messages for no reviews

Ratings - Lagging ratings + default message

---

hamza-server/views/order-placed.ejs
hamza-server/views/verify-confirmation.ejs
hamza-server/views/verify-email.ejs

Applied the new email footer to all current emails

added footer to email template

---

hamza-server/src/api/custom/discord/route.ts
hamza-server/src/api/custom/google/route.ts
hamza-server/src/api/custom/twitter/route.ts

hotfix: bad path

---

hamza-client/src/modules/account/components/verify/index.tsx
hamza-server/src/api/custom/discord/route.ts
hamza-server/src/api/custom/google/route.ts
hamza-server/src/api/custom/twitter/route.ts
hamza-server/src/utils/oauth/index.ts

- Added check for existing customer's use of email
- Fixed bug in redirect url creation

Verify fail success: improvements

---

hamza-client/src/modules/order/templates/shipped.tsx

Expected: 
- price is the price paid for the order, in crypto
Actual: 
- price is the price paid for the order, in crypto

crypto price

---

hamza-client/src/modules/account/components/cancel-card/index.tsx
hamza-client/src/modules/account/components/order-card/index.tsx
hamza-client/src/modules/account/components/processing-order-card/index.tsx
hamza-client/src/modules/account/components/shipped-card/index.tsx
hamza-client/src/modules/order/templates/processing.tsx
hamza-client/src/modules/order/templates/refund.tsx
hamza-client/src/modules/order/templates/shipped.tsx
hamza-client/src/modules/products/components/product-preview/components/product-description/index.tsx

- Cancel Bug Fix
- Set dynamic address in shipped
- removed courier in shipped && processing
- Commented out contact seller button
- capitalized eth in canceled
- Fixed price in refund page

bunch of small fixes

---

hamza-client/src/app/components/customer-icon/profile-image.tsx
hamza-server/src/services/buckydrop.ts
hamza-server/src/services/order.ts
hamza-server/src/services/regions.ts
hamza-server/src/services/smtp-notification-provider.ts
hamza-server/views/order-delivered.ejs
hamza-server/views/order-placed.ejs
hamza-server/views/order-shipped.ejs

Sending order emails for shipped & delivered orders

Order emails

---

hamza-client/src/modules/account/components/wishlist/components/wishlist-card.tsx
hamza-client/src/modules/products/components/cart-popup/index.tsx
hamza-client/src/modules/products/components/product-preview/components/summary/preview-checkout.tsx

- updated the cart to figma designs
- can now go to checkout or continue shopping
- works on mobile and desktop
- updated on wishlist and product detail page

Add to Cart modal - Wishlist and Product Preview Update

---

hamza-client/src/modules/account/components/wishlist/components/wishlist-card.tsx
hamza-client/src/modules/products/components/product-group-home/component/home-product-card.tsx
hamza-client/src/modules/shop/components/product-card.tsx

There was random characters in description I removed.

Fixes- Fixed wishlist card description, fixed small currency on cards

---

hamza-client/src/modules/account/components/cancel-card/index.tsx
hamza-client/src/modules/account/components/delivered-card/index.tsx
hamza-client/src/modules/account/components/processing-order-card/index.tsx
hamza-client/src/modules/account/components/refund-card/index.tsx
hamza-client/src/modules/account/components/reviews/index.tsx
hamza-client/src/modules/account/components/shipped-card/index.tsx
hamza-client/src/modules/products/components/product-preview/components/product-info/product-info.tsx
hamza-client/src/modules/products/components/product-preview/components/product-review.tsx
hamza-client/src/modules/products/components/product-preview/components/review-card-mobile.tsx
hamza-client/src/modules/products/components/product-preview/components/review-card.tsx
hamza-client/src/modules/products/components/product-preview/components/summary/preview-checkout.tsx
hamza-client/src/modules/products/components/product-price/index.tsx
hamza-client/src/modules/products/components/review-stars/index.tsx

Just only consolidated the several renderStars functions into one place, two different varieties. 
No design or layout changes unless they are unintentional.

Consistent review stars

---

hamza-client/src/modules/layout/templates/nav/menu-desktop/components/nav-searchbar.tsx

Double search bar on homepage: happened when we switched from default country 'us' to 'en'.

Double search bar

---

hamza-client/src/app/actions.ts
hamza-client/src/app/components/tweet/index.tsx
hamza-client/src/modules/account/components/cancel-card/index.tsx
hamza-client/src/modules/account/components/delivered-card/index.tsx
hamza-client/src/modules/account/components/processing-order-card/index.tsx
hamza-client/src/modules/account/components/refund-card/index.tsx
hamza-client/src/modules/account/components/reviews/index.tsx
hamza-client/src/modules/account/components/shipped-card/index.tsx
hamza-client/src/modules/products/components/product-price/index.tsx

- removed references to hard-coded 'us' country code
- removed references to demo.hamza.biz

removed references to hard-coded 'us' and 'demo.hamza.biz'

---

hamza-client/src/app/actions.ts
hamza-client/src/app/components/tweet/index.tsx
hamza-client/src/modules/account/components/cancel-card/index.tsx
hamza-client/src/modules/account/components/delivered-card/index.tsx
hamza-client/src/modules/account/components/processing-order-card/index.tsx
hamza-client/src/modules/account/components/refund-card/index.tsx
hamza-client/src/modules/account/components/reviews/index.tsx
hamza-client/src/modules/account/components/shipped-card/index.tsx
hamza-client/src/modules/products/components/product-preview/components/terms-of-service/product-details-tos.tsx
hamza-client/src/modules/products/components/product-price/index.tsx

Added 'ships from Shenzhen' to prod details page

Shipping info

---

hamza-client/src/app/actions.ts
hamza-client/src/app/components/tweet/index.tsx
hamza-client/src/modules/account/components/cancel-card/index.tsx
hamza-client/src/modules/account/components/delivered-card/index.tsx
hamza-client/src/modules/account/components/processing-order-card/index.tsx
hamza-client/src/modules/account/components/refund-card/index.tsx
hamza-client/src/modules/account/components/reviews/index.tsx
hamza-client/src/modules/account/components/shipped-card/index.tsx
hamza-client/src/modules/products/components/product-preview/components/terms-of-service/product-details-tos.tsx
hamza-client/src/modules/products/components/product-price/index.tsx

It was fixed, but only for the cancelled tab

Fix order variant images

---

hamza-client/src/app/components/scripts/chat-widget.tsx
hamza-client/src/modules/products/components/product-preview/components/product-description/index.tsx

Visit Home or Product Details
Check logs to see if there is an error "sanitize is not a function"

Move DOMPurify into useEffect - requires DOM to be present before call

---

hamza-client/src/modules/common/components/line-item/line-item-unit-price/index.tsx

Changes : 
1. Updated price calculation.
2. Added state variables for reducedPrice and hasReducedPrice to handle discount logic.
Test : 
1. Clear your browser cache (in chrome, its DevTools → Application → Storage → Clear Site Data)
2. Add an item to cart
3. Visit the cart page without logging in

HAMSTR-439 : Cart/Checkout Bug for new users (never logged in)

---

hamza-client/src/modules/checkout/actions.ts
hamza-client/src/modules/checkout/components/discount-code/index.tsx
hamza-client/src/modules/common/components/cart-totals/index.tsx

Check hamza-backend repo for description and testing steps

HAMSTR-432: Discount Codes

---

hamza-client/src/modules/common/components/line-item/line-item-unit-price/index.tsx

Unit price was showing total of line item, not single unit price.
**TEST**
1. Add item to cart
2. Go to cart page
3. Increment and decrement the quantity in cart
4. Unit price should stay at single unit price
5. Total item price will increment
Try with multiple items as well.

HAMSTR-451 - unit price fix

---

hamza-client/src/modules/account/components/profile/components/profile-form/components/profile-currency.tsx
hamza-client/src/modules/nav/templates/nav/menu-desktop/wallet-info-menu/currency-selector/index.tsx
hamza-client/src/modules/nav/templates/nav/menu-mobile/components/currency-selector.tsx

hotfix: build error

---

hamza-client/src/app/[countryCode]/(main)/order/confirmed/[id]/page.tsx
hamza-client/src/lib/server/enums.ts
hamza-client/src/lib/server/index.ts
hamza-client/src/modules/order-confirmed/index.tsx

NOTE:  Requires backend update as well
Updated thank you page design
Test by making a purchase and upon completion, you'll see the order complete page.

HAMSTR-324: Thank you page update

---

hamza-client/src/modules/checkout/components/payment/components/payment-button/index.tsx
hamza-client/src/modules/common/components/cart-totals/index.tsx

.env.local:
to show/hide bitcoin pay in checkout.
NEXT_PUBLIC_PAY_WITH_BITCOIN=true/false

use env to enable bitcoin pay

---

hamza-client/src/app/[countryCode]/(checkout)/checkout/page.tsx
hamza-client/src/app/[countryCode]/(checkout)/checkout/utils/fetch-cart-for-checkout.ts
hamza-client/src/app/[countryCode]/(main)/cart/page.tsx
hamza-client/src/app/[countryCode]/(main)/cart/utils/fetch-cart-for-cart.ts
hamza-client/src/lib/server/index.ts
hamza-client/src/modules/cart/components/empty-cart.tsx
hamza-client/src/modules/cart/components/item/index.tsx
hamza-client/src/modules/cart/components/store-items.tsx
hamza-client/src/modules/cart/templates/cart-template.tsx
hamza-client/src/modules/cart/templates/items-checkout-template.tsx
hamza-client/src/modules/cart/templates/items-template.tsx
hamza-client/src/modules/cart/templates/summary.tsx
hamza-client/src/modules/checkout/components/cart-items/index.tsx
hamza-client/src/modules/checkout/components/discount-code/index.tsx
hamza-client/src/modules/checkout/components/payment/components/payment-button/index.tsx
hamza-client/src/modules/checkout/templates/checkout-details/index.tsx
hamza-client/src/modules/checkout/templates/index.tsx
hamza-client/src/modules/checkout/templates/order-summary/index.tsx
hamza-client/src/modules/checkout/templates/payment-summary/index.tsx
hamza-client/src/modules/common/components/cart-totals/index.tsx
hamza-client/src/modules/common/components/delete-button/index.tsx
hamza-client/src/modules/common/components/line-item/line-item-price/index.tsx
hamza-client/src/zustand/cart-store/cart-store.ts

alignment of totals, shipping, discounts on:
- cart, checkout, order complete, order processing pages
Existing problem:
- discounts - discounts are applied on a per item basis, regardless of discount settings (allocation of total vs item is the same).
- Example:  1 item = $5, fixed discount of $1 applied, total discounted = $1 => pay amount = $4
- Example 2: 2 items, each $5, fixed discount of $1 applied, total discounted = $2 => pay amount = $3
- Example 3: 2 items, each $5, fixed discount of $10 applied, total discounted = $20 => pay amount = -$10 (error) - cannot checkout
- The negative total problem doesn't exist for percentages.
- You must be logged in.
**TEST**
- create discounts in tables - making sure these tables are updated:
- cart_discounts, discount, discount_rule, …

HAMSTR-473: consistent numbers display

---

hamza-client/cypress/e2e/headless/pages/product-details.cy.js
hamza-client/cypress/e2e/headless/pages/store.cy.js

2 tests require updating that tests link for "chat with them" links.

updated hns-chat as chat with them link

---

hamza-client/src/modules/order/components/order-timeline/index.tsx
hamza-client/src/modules/order/templates/processing.tsx
hamza-client/src/web3/contracts/escrow.ts

HAMSTR-427: Renamed Order 'histories' property to 'history'

---

hamza-client/src/modules/store/templates/store-content.tsx

**Changes:**
1. Fixed store navigation error by replacing Next.js router with direct window location navigation
2. Added early return after redirection to prevent rendering with invalid data
3. Added conditional rendering for StoreProductDisplay to prevent "map of undefined" errors
4. Improved error handling for invalid or missing store data
**Tests:**
1. Navigate to http://localhost:8000/en/store/xxxyyyz
2. Expected result: It redirects to the not-found page instead of showing a blank screen with errors
3. Verified no JavaScript errors in the browser console during navigation

HAMSTR-565 white page of death

---

hamza-client/src/lib/util/order-calculations.ts
hamza-client/src/modules/order/components/order-details.tsx
hamza-client/src/modules/order/components/order-overview/order-component.tsx
hamza-client/src/modules/order/components/order-timeline.tsx
hamza-client/src/modules/order/templates/delivered.tsx
hamza-client/src/modules/order/templates/order-completed-template.tsx
hamza-client/src/modules/order/templates/order-total-amount.tsx
hamza-client/src/modules/order/templates/processing.tsx
hamza-client/src/modules/order/templates/shipped.tsx
hamza-client/src/types/order.ts
hamza-client/src/web3/contracts/escrow.ts

Need to make sure the following data is consistent across pages:
- Shipping
- Discounts
- Order Subtotal
- Paid Total
Number consistency across pages fixed:
- Checkout page
- Order Confirmation page
- Order history/status page
- Escrow page
**TESTING**
- Create different orders
- multi store, multi item orders
- Single store multi item orders
- orders with fixed discount
- orders with % discount
Check the data across:
- Checkout page
- Order Confirmation page
- Order history/status page
- Escrow page

HAMSTR-584 - numbers not matching

---

hamza-client/package.json
hamza-client/src/modules/order/components/chain-enum/chain-enum.ts
hamza-client/src/modules/order/components/order-details.tsx
hamza-client/src/modules/order/templates/cancelled.tsx
hamza-client/src/modules/order/templates/delivered.tsx
hamza-client/src/modules/order/templates/dynamic-order-status.tsx
hamza-client/src/modules/order/templates/processing.tsx
hamza-client/src/modules/order/templates/refund.tsx
hamza-client/src/modules/order/templates/shipped.tsx

Problem:
- no order created date
- alignment issues
- HAMSTR-585 - fixed/update chain icon display
Fixed:
- order created date (adjusted to user timezone)
- alignment is now ok

HAMSTR-558 - order panel attention

---

hamza-client/src/app/[countryCode]/(main)/order/processing/[id]/page.tsx
hamza-client/src/modules/order-processing/index.tsx

Added 3 Jira tasks since they are all on the same page:
- HAMSTR-599 - QR Code button to open modal if closed
- HAMSTR-601 - Chain and currency added to popup modal
- HAMSTR-602 - Copy button for the payment amount
Test:
1. Do an async checkout
2. In payment processing page, check if all items above exist

HAMSTR-599, HAMSTR-601, HAMSTR-602 - payment processing updates

---

hamza-client/cypress/e2e/headed/features/checkout-address.cy.js
hamza-client/src/app/[countryCode]/(checkout)/checkout/page.tsx
hamza-client/src/app/[countryCode]/(checkout)/checkout/utils/fetch-cart-for-checkout.ts
hamza-client/src/lib/server/index.ts
hamza-client/src/modules/checkout/components/address-modal/index.tsx
hamza-client/src/modules/checkout/components/addresses/index.tsx
hamza-client/src/modules/checkout/templates/checkout-details/index.tsx
hamza-client/src/modules/checkout/templates/index.tsx
hamza-client/src/modules/checkout/templates/payment-summary/index.tsx

Problem:
- Address has several issues that needed to be addressed as outlined here - https://hamzamarket.atlassian.net/browse/HAMSTR-529?atlOrigin=eyJpIjoiYjI2ZTVkNWYwOThlNDMwY2I2YTExMWE2MmNkZDgwYjMiLCJwIjoiaiJ9
Test:
(A) New address without saving:
1. Create a new account
2. Create an order and goto checkout
3. Add a new address
4. After adding, address should be displayed
(B) New address with saving:
Repeat (A), but save address instead
(C) Check default address from previous checkout:
5. Add item to cart and go to checkout
6. Your previous address would be used as the current default (address + email)
(D) Check phone and email validation
- You should see that validation occurs on the input field already when doing A,B,C.

HAMSTR-529 address refactor

---

hamza-client/src/modules/order-processing/index.tsx

On mobile, QR code doesn't display fully on the page.  The QR code gets cutoff.
**TEST:**
1. Make an order and get to order processing page
2. Review the QR code modal popup and make sure the qr code isn't cutoff

HAMSTR-588 qr code modal

---

hamza-client/src/lib/server/index.ts
hamza-client/src/modules/products/components/product-group-store/index.tsx
hamza-client/src/modules/products/components/product-group/index.tsx
hamza-client/src/modules/shop/index.tsx
hamza-client/src/types/global.ts

**Motivation :** 
We have a lot more products now, and we want to continue to add more. Soon we will have more products than the homepage will bear. 
**Changes :** 
1. Implemented product pagination with "Load More" button functionality
2. Added API integration with limit and offset parameters for efficient data fetching
3. Created product accumulation logic to display all loaded products
4. Added empty state display when no products are found
**Tests:**
1. Tested implementation on homepage, store pages, and shop page
2. Configured homepage and store pages to display 24 products per page, and shop page to display 8 items per page
3. Verified "Load More" button functionality correctly loads additional products
4. For thorough testing, visit stores with more products than the initial page …

HAMSTR-608 lazy loading products

---

hamza-client/src/modules/checkout/components/address-modal/index.tsx

Allow plus sign in phone for address

Allow plus sign in phone

---

hamza-client/src/modules/checkout/components/payment/components/payment-button/index.tsx

Change "Pay with Crypto Wallet" to "Pay with Browser Wallet"

HAMSTR-637 : Change "Pay with Crypto Wallet" to "Pay with Browser Wallet

---

hamza-client/src/modules/cart/components/item/index.tsx

Changes : 
1. Wrapped the title in LocalizedClientLink - Now the title is clickable like the image
Test : 
1. Add some products to cart
2. Go to cart, click on the item title
3. Verify that it navigates to the correct product page

HAMSTR-647 : Clicking Product Title in Cart does Nothing

---

hamza-client/src/modules/products/components/product-group/index.tsx

Ooops.  This doesn't really affect anything unless you have the chrome debugger open.

removed debugger from code

---

hamza-client/src/modules/shop/components/desktop-filter-tags/filter-tags.tsx

**Changes:**
1. Fixed Clear All functionality in filter-tags.tsx
2. Updated to use useUnifiedFilterStore 
**Tests:**
1. Go to shop page
2. Select some categories
3. Click "Clear All"
4. Verify that categories are cleared

HAMSTR-652 : Clear All Button Doesn't Clear Filters on Shop Page

---

hamza-client/src/modules/nav/templates/nav/index.tsx
hamza-client/src/modules/nav/templates/nav/menu-mobile/components/cart-button.tsx
hamza-client/src/modules/nav/templates/nav/menu-mobile/components/search-button.tsx
hamza-client/src/modules/nav/templates/nav/menu-mobile/mobile-nav.tsx
hamza-client/src/modules/products/components/product-group/index.tsx
hamza-client/src/modules/search/components/mobile-hit/index.tsx
hamza-client/src/modules/search/components/mobile-hits/index.tsx
hamza-client/src/modules/search/templates/mobile-search-modal/index.tsx

Problem:
Mobile didn't have a search component.
**Test:**
1. Try the search component in the navbar (magnify icon)
2. Search result titles that matches with the keyword will hilight (bold)
3. Clicking result will bring you to product details page

HAMSTR-629 - search in mobile nav

---

hamza-client/src/modules/common/components/cart-totals/index.tsx

Changes:
1. Fixed cart totals showing 0.00 for prices ≥ $1,000
2. Removed Number() wrapper around formatCryptoPrice() calls in CartTotals component
3. Added helper function to safely parse formatted prices when needed for calculations
4. Updated TypeScript interface to handle mixed string/number types from formatCryptoPrice
Test:
1. Set product variant price to $1,000+ (e.g., $1,599)
2. Add item to cart and go to checkout
3. Verify cart totals display correctly as "1,599.00" instead of "0.00"
4. Test with prices <$1,000 to ensure no regression
5. Test currency conversion still works properly

HAMSTR-696 : Prices > 1,000 get Converted to 0.00

---

hamza-client/src/app/[countryCode]/(main)/products/[handle]/page.tsx
hamza-client/src/modules/products/components/product-card/index.tsx

**Changes**
1. Use encodeURIComponent for product handles in all product URLs and navigation.
2. Use decodeURIComponent for handles in /products/[handle]/page.tsx when fetching product data.
**Tests**
1. In the database, update a product’s handle to include reserved URL characters (e.g., @, $).
2. Visit http://localhost:8000/en/products/{handle} (replace {handle} with the actual handle).
3. Verify the product loads successfully.
Note: Handles containing # (hash) are not supported in URLs due to browser limitations.

HAMSTR-688 : Product handle issue with certain titles

---

hamza-client/src/lib/server/index.ts
hamza-client/src/modules/checkout/actions.ts
hamza-client/src/types/global.ts

Problem:
Discount code can be applied to cart even when it has past its limit.
Solution:
Create endpoint in backend to do validation for discount code
**Test:**
1. Create discount code with a limit of 1
2. Make 2 purchases with the same discount code (From same store)
3. The first one should be ok
4. For the 2nd order, when you try and add a discount code, you should get an error notice
**Bonus Note:**
Since a validation end point is used, other validations for a discount code will come from this endpoint, so date validation, expiry...etc will also be validated here.

HAMSTR-586 - validate discount code when applying discount code

---

hamza-client/src/modules/shop/components/desktop-filter-tags/filter-tags.tsx
hamza-client/src/modules/shop/components/desktop-side-filter/range-slider.tsx
hamza-client/src/modules/shop/components/mobile-filter-modal/components/filter-modal.tsx
hamza-client/src/modules/shop/components/mobile-filter-modal/components/range-slider-modal.tsx
hamza-client/src/zustand/home-page/home-filter/home-filter.ts
hamza-client/src/zustand/products/filter/product-filter.ts
hamza-client/src/zustand/products/filter/use-unified-filter-store.ts

**Motivation**
A new category on the homepage has products with high prices only. The product filter max is 350. So none of the products in that category were showing up. 
**Solution**
- pushed the max up to 5000
- replaced all the hard-coded mins and maxes for product filter to 2 centrally defined variables

HAMSTR-731: Products not Showing on Homepage

---

hamza-client/src/app/[countryCode]/(main)/layout.tsx
hamza-client/src/modules/nav/templates/faq/index.tsx

**Changes**:
1. Created a responsive FAQ component and added it to the homepage.
**Test**:
1. Navigate to the homepage.
2. Verify the component's layout matches the design on both desktop and mobile.

HAMSTR-729 : Adding an FAQ section on homepage

---

hamza-client/src/lib/server/index.ts
hamza-client/src/modules/home/components/search-and-filter-panel/index.tsx
hamza-client/src/modules/nav/templates/latest-products-arrivals-section/index.tsx
hamza-client/src/types/global.ts

Changes:
1. Implemented "Latest Arrivals" section.
2. Created the /custom/product/latest endpoint to fetch the latest products.
3. Data fetched from new backend endpoint for latest products.
4. "View all" button is now clickable but logs a console message instead of navigating.
Test:
1. Verify "Latest Arrivals" section 
2. Verify product details (name, price, image, reviews) are displayed correctly

HAMSTR-723 : Add Latest Arrivals on homepage

---

hamza-client/src/modules/home/components/hero-banner/index.tsx

Updated header notification text:
"Shop Smarter with Hamza! Use Bitcoin, stablecoins, and more — instantly. Learn more! "
https://hamzamarket.atlassian.net/jira/software/projects/HAMSTR/boards/6?selectedIssue=HAMSTR-744

HAMSTR-744 - updated notification text

---

hamza-client/src/modules/categories/components/category-grid.tsx

**Motivation**
We don't have a 'Games' category, so I am removing it. I don't really have a replacement for it, so I'm just going to leave it out. Hopefully it looks ok. 
**To Test**
Does it look ok?

HAMSTR-739: Remove 'Games' Category Icon

---

hamza-client/src/modules/checkout/components/payment/components/payment-button/index.tsx

Changes:
1. Added balance check for "Pay with External Wallet" before redirecting to payment processing
2. Created checkBalanceBeforePayment function to verify wallet balance without requiring transaction signing
3. Added "Insufficient balance" error display for direct payments with insufficient funds
Test:
1. Connect wallet with insufficient funds for selected currency
2. Click "Pay with External Wallet" - should show "Insufficient balance" error instead of redirecting
3. Click "Pay with Browser Wallet" - should show "Insufficient balance" error without requiring signature

HAMSTR-735 : Mobile: Insufficient Funds error not Showing?

---

hamza-client/src/modules/common/components/filter-radio-group/index.tsx
hamza-client/src/modules/search/components/search-product-card-group/index.tsx
hamza-client/src/modules/search/templates/search-results-template/index.tsx

Display of search result updated to resemble "shop" page results.
**Test:**
1. Visit locally - http://localhost:8000/en/results/games
2. This should have a few results
3. Review layout and switch currency to see if all numbers ok
NOTE: Sorting isn't working properly.  This needs more work.  At the moment don't have much time.  BUT, the old one also didn't work.

HAMSTR-748 - misc updates to fix pricing display

---

hamza-client/src/modules/home/components/search-and-filter-panel/components/filter-bar/FilterBar.tsx
hamza-client/src/modules/shop/components/filter-bar/filter-bar-store.tsx

**Motivation**
According to Luciano, when we scroll the product categories list…
**Changes:**
1. Add Framer Motion slide animation to FilterBar categories (home page).
2. Add the same animation to FilterBarStore (shop page).
**Test:**
1. Click the right chevron in home and shop filter bars: categories slide smoothly.
2. "All" button does not move during animation.
3. Layout, scroll, and chevron logic unchanged everywhere.

HAMSTR-755 : Scrolling Carousel of Categories - No Motion

---

hamza-client/package.json
hamza-client/src/app/[countryCode]/(main)/giftcards-promo/page.tsx
hamza-client/src/modules/giftcards-promo/components/category-section.tsx
hamza-client/src/modules/giftcards-promo/components/comparison-table.tsx
hamza-client/src/modules/giftcards-promo/components/conparison-table.tsx
hamza-client/src/modules/giftcards-promo/components/final-section.tsx
hamza-client/src/modules/giftcards-promo/components/hero-section.tsx
hamza-client/src/modules/giftcards-promo/components/how-it-works-section.tsx
hamza-client/src/modules/giftcards-promo/components/payment-methods-section.tsx
hamza-client/src/modules/giftcards-promo/components/popular-brands-section.tsx
hamza-client/src/modules/giftcards-promo/components/why-choose-section.tsx
hamza-client/src/modules/giftcards-promo/index.tsx

**Motivation** 
We have a new landing page design for gift card promotions. 
**Changes**
1. Create new landing page for gift card promo for desktop and mobile view.
**Test**
1. Run yarn install
2. Go to http://localhost:8000/en/giftcards-promo
3. Verify page matches Figma design
4. Test responsive design on mobile/tablet

HAMSTR-752 incorporate new landing page

---

hamza-client/src/modules/twitter/templates/twitter-feed.tsx

**Ref**
https://www.bitrefill.com/th/en/
**Changes:**
1. Replaced scrollbar with auto-scroll animation (right-to-left)
2. Added hover to pause animation
3. Implemented drag functionality with position persistence
4. Created infinite loop with seamless wrapping
**Test:**
1. Verify auto-scroll moves cards left continuously
2. Confirm hover pauses animation without card jumping
3. Test drag left/right maintains position after release
4. Check infinite scroll works in both directions

HAMSTR-757 : Animation for Twitter Feed Scroll (see Bitrefill)

---

hamza-client/src/modules/twitter/templates/twitter-feed.tsx

Motivation : 
1. Problem: Continuous requestAnimationFrame loop running 
2. Impact: Whole project becomes slow and unresponsive
3. Root Cause: Heavy state updates during animation triggering excessive re-renders
Changes:
1. Memoized calculations (cardWidth, totalWidth, duplicatedTweets)
2. Optimized event handlers with useCallback to prevent recreation
3. Added animation timing control to reduce unnecessary state updates
Test:
1. Verify dragging works in both directions
2. Check hover pause/resume functionality
3. Test touch dragging on mobile devices
4. Confirm overall project responsiveness improved

HAMSTR-779 : Twitter Feed Animation Performance Issue

---

hamza-client/src/modules/products/components/product-preview/components/image-gallery/image-display/preview-gallery.tsx
hamza-client/src/modules/products/templates/index.tsx

**Changes:**
1. Fixed mobile overflow in PreviewGallery component by reducing grid gaps and using proper width constraints
2. Replaced calc(100% - 2rem) container width with padding approach in ProductTemplate
3. Added responsive max heights and smaller thumbnail sizes for mobile view
4. Used consistent width="100%" and AspectRatio components for better responsive behavior
Test:
1. Verify no horizontal overflow on mobile devices (320px - 768px)
2. Confirm desktop layout remains unchanged
3. Test image gallery modal opens correctly on both mobile and desktop
4. Check back button and menu positioning on mobile

HAMSTR-790 : Gift card (Visa) running over margins on Mobile

---

hamza-client/src/modules/home/components/hero-banner/index.tsx

**Changes:**
1. Updated hero banner text
2. Changed hero banner link from external blog to /seller page
**Test:**
1. Verify hero banner shows new seller-focused message
2. Confirm banner links to /seller page when clicked

HAMSTR-795 : Link to /seller page

---

hamza-client/src/modules/nav/templates/footer/index.tsx

**Changes:**
1. Added YouTube icon import to footer component
2. Added YouTube link to social media section in footer
**Test:**
1. Visit any page and scroll to footer
2. Verify YouTube icon appears with other social media icons
3. Click YouTube icon to confirm it opens correct channel

HAMSTR-800 : Social Media Links: Link to YT channel

---

hamza-client/src/modules/categories/components/category-banner/index.tsx

**Changes:**
1. Removed "Save Up to xx% on Fees" text from category banner component
**Test:**
1. Navigate to any category page and verify the fees text is no longer displayed

HAMSTR-802 : xx% in category pages subtext

---

hamza-client/src/modules/nav/templates/footer/index.tsx

**Changes :**
1. Added brand colors to social media icons 
2. Enhanced hover effects with scaling, rotation, glow shadows, and background fill animations
3. Added tooltips 
**Test :**
1. Navigate to footer and hover over social media icons
2. Verify tooltips appear with correct labels
3. Check all social media links redirect properly

HAMSTR-801 : Make social media links more visible/colorful
