LoadPipe/Hamza-medusa

hamza-client/src/modules/checkout/components/payment-button/index.tsx
hamza-server/src/index.d.ts
hamza-server/src/models/store.ts
hamza-server/src/models/user.ts
hamza-server/src/services/crypto-payment-provider.ts

A couple of changes were necessary to get the server side at checkout time to determine the correct wallet address to use, based on the wallet address associated with the stores from which products are being purchased, then to pass that back to the client so that it could be passed to the Switch as the receiver of funds. 
- Models had to be adjusted to appease TypeORM standards, so that service queries could easily retrieve the store via the Product, and the User via the Store with the minimum amount of querying. 
- The Crypto payment processor was modified so that it would make those queries to retrieve the appropriate wallet addresses, and pass them back to the client at the start of the payment session. 
- The Crypto payment button and related code was modified to retrieve the wallet …

Payment receiver is determined dynamically at payment time

---

hamza-server/src/services/crypto-payment-provider.ts

Two issues: 
1. Occasionally, transaction would not be verified in time (race condition; the RPC provider sometimes might not register the new TX fast enough)
2. The query for cart data was encountering a deadlock with medusa's write operations to the DB. There should be a way to mark this query as "read only"; a read operation should not cause a deadlock. Even though this is fixed for now, I feel we'll encounter it again and we'll need to discover how to mark these typeorm queries (relations) as read-only

fixed bug: crypto payment backend stumbling over itself

---

hamza-client/src/modules/checkout/components/payment-button/index.tsx
hamza-server/src/migrations/1907365738273-MultiVendorOrder.ts
hamza-server/src/models/order.ts
hamza-server/src/services/order.ts
hamza-server/src/strategies/cart-completion.ts

properly writing to payment table
removed tx_id from order table
investigated the viability of adding cart_id to payment table
I think it's not possible, but it is accessable through order, which is related to payment, so maybe redundant anyway?
other suggestions welcome.

Staging payment order crud

---

hamza-client/src/lib/data/index.ts
hamza-client/src/modules/cart/actions.ts
hamza-client/src/modules/cart/components/item/index.tsx
hamza-client/src/modules/cart/templates/items.tsx
hamza-client/src/modules/cart/templates/preview.tsx
hamza-client/src/modules/common/components/line-item-price/index.tsx
hamza-client/src/modules/common/components/line-item-unit-price/index.tsx
hamza-client/src/modules/order/components/item/index.tsx
hamza-client/src/modules/products/components/product-actions/index.tsx
hamza-server/src/migrations/1894875825785-LineItem.ts
hamza-server/src/models/line-item.ts
hamza-server/src/services/cart.ts
hamza-server/src/strategies/cart-completion.ts

This is concerned with mainly adding currency_code to LineItem, so that each line item, as it's added to the cart, has the currency already recorded. That way at checkout time, instead of calculating the correct currency to use, the currency will be just there in the line item. 
It will also be the basis for fixing price totals for cart. 
- LineItem extended on server side with currency_code
- LineItem extended on client side with currency_code
- LineItem given currency code when addded to cart 
- correct display of prices (with currency) in cart 
- updated CartCompletionStrategy to use line item currencies & prices

Selecting Prices for Checkout

---

hamza-client/src/modules/checkout/components/payment-button/index.tsx
hamza-client/src/modules/common/components/cart-totals/index.tsx
hamza-server/data/seed.json

- cleaned up/ reorganized checkout on the client side (mainly)
- removed Manual payment method (we never use it)
- if checkout fails for any reason (error or rejected), button becomes enabled again 
- if checkout fails for any reason (error or rejected), message is displayed
- inventory updated only on successful checkout 
- added comments on payment-button page to clarify functions & code in general

Fixed bug: Checkout button not cancelling (and Checkout cleanup) 

---

hamza-client/src/lib/data/index.ts
hamza-client/src/modules/account/actions.ts
hamza-client/src/modules/checkout/components/payment-button/index.tsx
hamza-client/src/modules/checkout/components/payment/index.tsx

The issue was that anonymous users going to checkout would encounter hard-crash errors on the way, preventing them from even getting to checkout. 
1. put cookie handling into a try/catch
2. requiring wallet connection on the 'review' step, rather than right at checkout; this is more efficient

Fixes to allow anonymous (not logged in) checkout

---

hamza-client/src/modules/checkout/components/shipping-address/index.tsx

- Deleted the red asterisk removing email as a required field (field is now optional)
- If the user's profile email address ends with @evm.blockchain, the email input field is now empty
- If the user's profile email address does not end with @evm.blockchain, the email is displayed
- Added email input validation - if email is not correctly formatted it displays an error message underneath the input
- Error message deletes onFocus or if field is empty

Checkout email bug

---

hamza-client/src/modules/account/components/order-overview/index.tsx
hamza-client/src/modules/products/components/product-review/index.tsx

API calls from the front end, when they just hard-code "localhost", fail when deployed to AWS. They should follow the convention of using: 
```
const MEDUSA_SERVER_URL =
process.env.NEXT_PUBLIC_MEDUSA_BACKEND_URL || 'http://localhost:9000';
```

Api call fixes

---

hamza-client/src/app/[countryCode]/(main)/account/@login/page.tsx
hamza-client/src/app/[countryCode]/(main)/account/layout.tsx
hamza-client/src/modules/account/components/login/index.tsx
hamza-client/src/modules/account/components/register/index.tsx
hamza-client/src/modules/cart/components/sign-in-prompt/index.tsx
hamza-server/src/api/custom/verify/route.ts

When user is created anonymously, we used to give them first/last names that were substrings of their wallet address. 
Now they have a default first/last name.

Changed default anonymous customer first/last name

---

hamza-client/src/lib/util/prices.ts

This one small issue was breaking product page; 'amount' sometimes might not be number, so converting it to one

Client build fixes: Breaking product page

---

hamza-client/src/modules/checkout/components/payment-button/index.tsx

The wrong variable for cart id was being passed to finalizeCheckout from the front end. Now the right one is.

Bug: cart id undefined in finalizeCheckout

---

hamza-client/src/modules/home/components/product-layout/index.tsx
hamza-client/src/modules/products/components/product-card-group/index.tsx

Passing to product card variant.prices[0], but it should have been choosing that price that matches the preferred currency. Now it's better.

homepage price fixes

---

hamza-client/src/app/components/tweet/index.tsx

"Tweet this product" text next to X button just so users know what they're doing. However, the alignment is off.

tweet this product text next to X

---

hamza-client/src/modules/cart/actions.ts
hamza-client/src/modules/products/components/mobile-actions/index.tsx
hamza-client/src/modules/products/components/product-actions/index.tsx

- fixed bug: if for some reason your countryCode is not valid (which is a code smell), but if FORCE_US_COUNTRY is true, add to cart from prod detail page will still work. 
- make 'Add to Cart' text consistent (vs. 'Add to cart')

force us country code when add to cart

---

hamza-client/src/app/[countryCode]/(checkout)/checkout/page.tsx
hamza-client/src/app/[countryCode]/(checkout)/not-found.tsx
hamza-client/src/app/[countryCode]/(main)/cart/not-found.tsx
hamza-client/src/app/[countryCode]/(main)/cart/page.tsx
hamza-client/src/app/[countryCode]/(main)/not-found.tsx
hamza-client/src/app/not-found.tsx
hamza-client/src/modules/cart/actions.ts
hamza-client/src/modules/checkout/actions.ts
hamza-client/src/modules/checkout/components/shipping/index.tsx
hamza-client/src/modules/checkout/templates/checkout-form/index.tsx
hamza-client/src/modules/checkout/templates/checkout-summary/index.tsx
hamza-client/src/modules/layout/components/cart-button/index.tsx

Missing cart id (unretrievable from cookies  in production build for some reason) causing blank page in checkout. 
Fixed by passing the cart Id around, instead of retrieving from cookies (in a few select places)

Checkout: missing cart Id on Delivery Step

---

hamza-client/src/modules/checkout/components/payment-button/index.tsx

If window.ethereum is not present, then checkout will just go through 
This is a good fix for non-wallet-having users who are just curious, as well. 
For actual mobile checkout, another fix will be needed; but this is a good start.

Hack for mobile checkout

---

hamza-client/src/store/wishlist/wishlist-store.tsx

It looks like this is what's happening: 
- normally, the wishlist creation and management is happening just fine 
- when the 'onRehydrateStorage' handler in wishlist-store.tsx (just search for 'onRehydrateStorage') is getting called, it's getting the wrong customer_id. Then it's trying to create a wishlist for that customer, which maybe doesn't exist. 
- the wrong customer id is coming from localStorage, '__hamza_customer'. As far as I can see, customer data isn't stored in localStorage, and that __hamza_customer key is not used anywhere else. If true, then it will never contain anything real. 
- maybe localStorage.__hamza_customer was once used, but it appears to no longer be 
- in that case, what to do in the onRehydrateStorage routine? Is it still needed? …

commented out the 'onRehydrateStorage' handler for wishlist

---

hamza-server/src/api/custom/order/customer-orders/route.ts
hamza-server/src/services/__tests__/order.ts
hamza-server/src/services/order.ts
hamza-server/src/test/__mocks__/productService.ts
hamza-server/src/test/__tests__/getProducts.test.js

- added new route: GET custom/orders/customer-orders
The purpose of this route is to support the new customer orders display, in which orders are grouped into buckets "To Pay", "To Receive", etc. This will use server-side logic to group the orders into buckets for you, and return them already grouped. 
it works like this: 
?customer_id= (required) 
?buckets=true (or omit - if passed, then it will return the orders divided up into buckets; otherwise, it will just return an array of orders) 
output is in this form: 
{
'ToPay': [... orders], 
'ToShip': [..orders], 
... etc. 
}
- OrderService methods have been added to support this route 
- unit test stubs have been added, but need more work

Order Bucket route

---

hamza-client/src/modules/checkout/components/payment-button/index.tsx
hamza-server/src/migrations/2849489248999-Whitelist.ts
hamza-server/src/models/whitelist.ts
hamza-server/src/services/cart.ts
hamza-server/src/services/whitelist.ts
hamza-server/src/strategies/checkout-processors/basic-checkout.ts
hamza-server/src/strategies/price-selection.ts

if the appropriate .env variable is set on hamza-server side, then whitelisting by store is required at checkout time, in order to check out. Whitelisting is done by adding an entry to the white_list table with the wallet_address of the whitelisted customer and a store_id of the store. 
When whitelisting is turned on, failure to be on the whitelist at checkout will result in checking failing. CompleteCart will fail with a 401 (unauthorized).

Store whitelist at checkout

---

currency-conversion/src/coin-gecko.service.ts

Allow coingecko conversions between cny and other currencies, including eth, USDC, USDT, etc. 
Allow the same for any other fiat currencies (not just cny)

Rmb convert

---

hamza-server/src/services/whitelist.ts

Whitelist fix to support mini-demo: check for whitelistedness at checkout must be case-insensitive.

whitelist fix: case insensitive check

---

hamza-client/src/lib/data/index.ts
hamza-client/src/modules/order/templates/all.tsx
hamza-server/src/api/custom/order/cancel/route.ts

Improved the Order Cancellation situation. Still a few things to do but it submits the form, and cancels the order. 
I'm not sure why orders are keying off of "cart_id" everywhere, but they should be done by order id. We do not need to give a shit about what cart they were in, after the order has been placed.

Cancel shenanigans

---

currency-conversion/src/coin-gecko.service.ts

Currency exchange rate caching in currency-conversion REST service was triggered as soon as the old cache expired. 
If many requests came in at once (as they often do), then they would all find the cache to be expired at once, and would cause multiple concurrent cache refreshes, causing the 429 rate-limit error to trigger. 
Now a flag is set as soon as cache refresh begins, and any thread that finds that flag set will just use the old expired rate in the meantime.

Currency exchange rate service caching

---

hamza-client/src/modules/account/components/review-page/index.tsx

The text was overflowing off the buttons, I fixed that using the ingenious method called 'making the text shorter' cause you know, I'm a stable genius. Check this out: 
- person
- woman 
- man
- camera
- tv

shortened text of buttons so that they don't overflow

---

hamza-server/src/services/buckydrop.ts

Wrong status for bucky order details: 6 should mean 'shipped'

buckydrop status error: 6 is shipped

---

hamza-server/src/api/middlewares.ts
hamza-server/src/api/route-handler.ts
hamza-server/src/migrations/2986572957694-AppLogs.ts
hamza-server/src/models/app-log.ts
hamza-server/src/utils/context.ts
hamza-server/src/utils/logging/logger.ts

Logging: 
- session_id, request_id, and customer_id fields added 
- request id and customer id fields calculated by middleware and cached in async storage 
- logger uses the values (contextual values) in log entry
In short, it associates requests together, and with a customer id where relevant & possible

logging level 2: session, request, and customer ids

---

hamza-server/src/services/buckydrop.ts
hamza-server/src/services/cart.ts
hamza-server/src/strategies/price-selection.ts

Wrong price but correct currency on cart/checkout: 
Race condition. The price was taking a while to retrieve, but the currency of the cart item had already been set to the new currency. Whilst waiting for the price, other threads tried to do the same thing. It's 'fixed' now but needs atomicity. It could potentially recur.

fixed price bug: race condition

---

hamza-server/src/api/custom/bucky/orders/route.ts
hamza-server/src/api/custom/bucky/track/route.ts
hamza-server/src/api/custom/checkout/route.ts
hamza-server/src/api/custom/config/route.ts
hamza-server/src/api/custom/order/customer-order/route.ts
hamza-server/src/index.d.ts
hamza-server/src/migrations/3595867849494-BuckyOrder.ts
hamza-server/src/migrations/5828595666725-BuckyProduct.ts
hamza-server/src/models/order.ts
hamza-server/src/models/product-variant.ts
hamza-server/src/models/product.ts
hamza-server/src/services/buckydrop.ts
hamza-server/src/services/order.ts
hamza-server/src/services/product.ts
http-client/local-dev.http

- Orders for bucky are no longer created automatically at checked, but just marked as 'pending' 
- A new route exists to pull pending bucky orders
- A new route exists to process pending bucky orders (separately from checkout) 
- Later this can be automated thusly: after an automated async process verifies orders on chain, bucky drop orders can be automatically processed 
- Changed all bucky_metadata columns (product, variant, and order) to jsonb (from string)

New bucky order handling

---

hamza-client/src/lib/data/index.ts
hamza-client/src/modules/checkout/components/payment-button/index.tsx
hamza-server/src/api/custom/cart/cancel/route.ts

Fixed bug: cancelOrderFromCart on client side not succeeding
- some issues on server side 
- headers not passed from client side
- parameter passed incorrectly on client side 
- moved call back to client side to avoid stackoverflow

fixed bugs causing cancelOrderFromCart to not succeed when it should

---

hamza-client/src/modules/products/components/product-preview/components/image-gallery/gallery-modal/index.tsx
hamza-client/src/modules/products/components/product-preview/components/preview-gallery.tsx

- fixed dimensions on desktop and carousel
The dimensions were off. The way they designed it was for a smaller width than the rest of the content. I reached out to UX to see if this was their intention but this is more accurate now. I also fixed the gallery modal for lower screen sizes.

Product image gallery - fixed dimensions on desktop and carousel

---

hamza-client/src/lib/util/get-product-price.ts
hamza-client/src/modules/checkout/components/shipping-address/index.tsx

Fixed bug: 
- when at checkout, and not logged in, customer has no shipping addresses. Therefore the client-side query for customer.shipping_addresses fails. Just added conditional dot. (?.)

fixed bug, manifests when user not logged in at checkout

---

hamza-client/src/modules/cart/templates/items.tsx

Fixed bug: "continue shopping" button on empty cart should direct to /shop, not /store

shop not store

---

hamza-client/src/lib/data/index.ts
hamza-client/src/modules/checkout/components/payment-button/index.tsx
hamza-client/src/modules/checkout/components/payment-button/payment-handlers.ts
hamza-server/src/api/admin/custom/payments/verify/route.ts
hamza-server/src/api/custom/checkout/route.ts
hamza-server/src/api/custom/store/categories/route.ts
hamza-server/src/api/route-handler.ts
hamza-server/src/contracts.config.ts
hamza-server/src/migrations/9204848284827-Payment.ts
hamza-server/src/models/payment.ts
hamza-server/src/services/order.ts
hamza-server/src/services/payment-verification.ts
hamza-server/src/web3/abi/erc20-abi.ts
hamza-server/src/web3/abi/lite-switch-abi.ts
hamza-server/src/web3/abi/massmarket-payment-abi.ts
hamza-server/src/web3/abi/switch-abi.ts
hamza-server/src/web3/contracts/lite-switch.ts
hamza-server/src/web3/index.ts

This is a new way of handling payments, and affects buckydrop. 
Once upon a time, buckydrop products were ordered from buckydrop as soon as checkout was complete. 
Now, they get a 'pending' status in their buckydrop metadata. 
Later, a separate process will sweep the blockchain to verify payments whose status is 'AWAITING', and change the payment status to 'CAPTURED' once the payment has been verified. 
Payments are verified by scanning events emitted by the LiteSwitch. 
Once a buckydrop payment has been verified (if it was a buckydrop order), then the order is placed with buckydrop.

Payment verify

---

hamza-client/src/modules/account/components/wishlist/components/wishlist-card.tsx
hamza-client/src/modules/common/components/cart-totals/index.tsx
hamza-client/src/modules/common/components/line-item-price/index.tsx
hamza-client/src/modules/home/components/product-layout/components/product-card.tsx
hamza-client/src/modules/home/components/search-and-filter-panel/components/filter-bar/components/CurrencyModalButton.tsx
hamza-client/src/modules/order/components/summary/index.tsx
hamza-client/src/modules/order/components/transaction-details/index.tsx
hamza-client/src/modules/products/components/product-actions/index.tsx
hamza-client/src/modules/products/components/product-group-home/component/home-product-card.tsx
hamza-client/src/modules/products/components/product-group-store/index.tsx
hamza-client/src/modules/products/components/product-preview/components/currency-buttons.tsx
hamza-client/src/modules/products/components/product-preview/components/preview-checkout.tsx
hamza-client/src/modules/shop/components/currency-button.tsx
hamza-client/src/modules/shop/components/filter-tags.tsx
hamza-client/src/modules/shop/components/mobile-filter/components/currency-modal-button.tsx
hamza-client/src/modules/shop/components/product-card.tsx

This fixes two issues: 
1. when not logged in and after clearing cookies, homepage prices are funky
2. when not logged in and after clearing cookies, broken currency icon on prod details page
In the future, always make 'usdc' the ?? fallback for preferred_currency_code; keep in mind that null/undefined preferred_currency_code is a normal condition

Fixed price shenanigans and Broken Currency Icon Image

---

hamza-server/src/services/order.ts

When selecting orders to display on customers order page, only select those which have items (to avoid that blank horizontal line section)

Select only orders with items

---

hamza-client/src/app/[countryCode]/(main)/products/[handle]/page.tsx

Compiling every page with every country code killls the server during client build, and isn't necessary in any way for any reason.

force us country code only during compilation

---

hamza-client/src/modules/home/components/search-and-filter-panel/components/filter-bar/components/FilterModal.tsx
hamza-server/src/api/custom/bucky/verify/route.ts
hamza-server/src/api/custom/product/filter/route.ts
hamza-server/src/services/product.ts
hamza-server/src/utils/cache/seamless-cache.ts
hamza-server/src/utils/filter-duplicates.ts

This is an emergency measure so that I can add products for right now without slowing down the server. 
This caches the product category query results, as those are taking quite a while to retrieve all of the variants (many variants)
Working on a better solution in the meantime.

Product query optimize

---

hamza-server/src/api/custom/checkout/route.ts
hamza-server/src/services/order.ts
hamza-server/src/services/product-review.ts
hamza-server/src/services/product.ts

- initial order status is now REQUIRES_ACTION (unused status)
- only the most recent order is retrieved from checkout 
- that cancelling failed order from the frontend is now no longer necessary (but not removed)
- failed orders that weren't cancelled for whatever reason will no longer show up in customer orders

Initial order status

---

hamza-client/src/modules/products/components/product-preview/components/preview-checkout.tsx

Wrong Product Image Showing fixed by resetting state in parent component

Fix: Wrong Product Image Showing

---

hamza-client/src/modules/account/components/processing-order-card/index.tsx
hamza-server/src/services/order.ts

After recent order changes: 
- order status must be set to PENDING in finalizeCheckout 
- order from cart must be retrieved in a different way

hotfixes for recent order change

---

hamza-client/src/modules/layout/templates/nav-4/index.tsx

Ok I fixed the routing error when going from error page to home page. I switched localizedlink to an <a> element. Not sure if the countryCode in the url was causing issues. Be aware of this if having routing issues: 
const LocalizedClientLink = ({
children,
href,
...props
}: {
children?: React.ReactNode;
href: string;
className?: string;
onClick?: () => void;
passHref?: true;
[x: string]: any;
}) => {
const { countryCode } = useParams();
return (
<Link href={`/${countryCode}${href}`} {...props}>
{children}
</Link>
);
};
export default LocalizedClientLink;

Intermittent errors in /account section - fix

---

hamza-client/src/modules/account/components/wishlist/components/wishlist-card.tsx
hamza-client/src/modules/account/components/wishlist/index.tsx
hamza-client/src/modules/home/components/product-layout/components/product-card.tsx
hamza-client/src/modules/products/components/product-actions/index.tsx
hamza-client/src/modules/products/components/product-preview/components/product-info.tsx
hamza-client/src/store/order-tab-state/index.ts
hamza-client/src/store/wishlist/wishlist-store.tsx

Fixed currency issues with wishlist items. By adding wishlist items with their entire price dictionary, rather than just with a single price amount. 
Storing prices is not the best idea though, as the prices will go stale in the wishlist. But presumably this will correct itself when the items are added to the cart.

Wishlist prices fix

---

hamza-client/src/modules/products/components/product-preview/components/product-info.tsx
hamza-client/src/store/wishlist/mutations/wishlist-mutations.tsx
hamza-client/src/store/wishlist/wishlist-store.tsx

The correct variant is indeed being added to the wishlist. 
But the price associated with it is always the price of the first variant; that's fixed.
When a variant is removed from wishlist, it's removed by product id. This removed the bug in which the item won't remove itself unless you select the correct variant before removing it.

fix for wishlist variant price: price should match the selected variant

---

hamza-client/src/modules/common/components/localized-client-link/index.tsx
hamza-client/src/modules/products/templates/index.tsx

Back to Products now goes one route back... 
- LocalizedClientLink edited;
- href optional now; if not set, router.back gets called.. 
- Edge case covered: if they have no history and load the page on a random product page... route back to home page.

[LHF] Back to products behavior

---

hamza-client/src/modules/cart/components/item-checkout/index.tsx
hamza-client/src/modules/cart/components/item/index.tsx

In cart and checkout, show the product variant image if one is available; otherwise show the product.thumbnail.

Show variant image in cart/checkout if available

---

hamza-server/src/api/custom/discord/route.ts
hamza-server/src/api/custom/google/route.ts
hamza-server/src/api/custom/twitter/route.ts

Fix for a bug that could cause an inability to log in after verifying account: emails from account verification must be lowercase

bug fix: emails must always be lowercase

---

hamza-client/src/modules/products/components/product-preview/components/product-info/product-info.tsx

When there is a null rating, the product details page crashes

fix for null rating

---

hamza-client/src/modules/account/components/verify/index.tsx
hamza-server/src/api/custom/twitter/route.ts

The 'fix' here is to remove the Twitter OAuth button from the site; with our current API access, it doesn't look like we can get the user's email, which is literally all that we want. 
If this changes then I will reenable the button.

Twitter oauth fix

---

hamza-client/src/app/components/providers/rainbowkit/rainbow-provider.tsx
hamza-client/src/lib/data/index.ts

This is preventing 'ghost login', which is a phenomenon marked by disconnected wallet, but an active cart and ability to see the account profile page. 
Though I have not seen this issue recently, I do believe it can still happen. And while this change comes with some risk, I think it's worthwhile. 
This only goes through the getCustomer routine in rainbow wrapper if there is a wallet connected.

prevent ghost logins

---

hamza-client/next.config.js

Urls with /us/ as the country code will have it changed to /en/

redirect /us/ path to /en/

---

hamza-client/package.json
hamza-client/src/app/[countryCode]/(main)/order/processing/[id]/page.tsx
hamza-client/src/modules/checkout/components/discount-code/index.tsx
hamza-client/src/modules/checkout/components/payment/components/payment-button/index.tsx
hamza-client/src/modules/checkout/templates/payment-summary/index.tsx
hamza-client/src/modules/common/components/cart-totals/index.tsx
hamza-client/src/modules/common/components/modal-cover-wallet-connect/index.tsx
hamza-client/src/modules/order-processing/index.tsx

BTC WIP
Checkout page:
- checkout has btc button, clicking will direct to payment processing page with qr code modal open
- btc fake calculated amount
Payment processing page:
- payment processing handles btc using paywith param (probably should come from payment object) 
- payment processing opens modal with openqrmodal param (think this should be ok in live)
- button to open btc modal if paywith is bitcoin
**TEST:**
- To view the payment process page - if async flow isn't set - with no order create yet - you'll need to have a completed checkout, then use the cart id of a previous order and visit:
http://localhost:8000/en/order/processing/[cart_id]?paywith=bitcoin&openqrmodal=true

HAMSTR-371: Bitcoin UI

---

hamza-client/src/app/[countryCode]/(main)/order/processing/[id]/page.tsx
hamza-client/src/modules/checkout/components/payment/components/payment-button/index.tsx
hamza-client/src/modules/checkout/components/payment/components/payment-button/payment-handlers/async.ts
hamza-client/src/modules/order-processing/index.tsx

**Motivation**
Shortening the wait time, now we want to redirect to thankyou page (consider the payment to be 'complete' as far as the customer's concerned) as soon as it's received in the payment wallet; not waiting until it's in escrow. 
**Changes**
1. Redirects to checkout when status hits "Received", rather than "In Escrow" (as before)
2. To ensure that users can use this page outside of the checkout process, it now takes a "?checkout" querystring parameter. If true, it will redirect when the status reaches 'received'; otherwise, it will just stay on the page indefinitely.
3. The status refresh (status panels) weren't refreshing in reaction to actual real-time changes from the server, but were only showing the true payment status on first page load.

HAMSTR-466: Payment Processing Page

---

hamza-client/src/app/components/loaders/hamza-logo-loader.tsx
hamza-client/src/modules/cart/components/item/index.tsx
hamza-client/src/modules/checkout/components/payment/components/payment-button/index.tsx
hamza-client/src/modules/checkout/templates/checkout-details/index.tsx
hamza-client/src/modules/checkout/templates/order-summary/index.tsx
hamza-client/src/zustand/cart-store/cart-store.ts

Problem:
This allowed me to manipulate the checkout process by hijacking the cover (control hide/show behavior - weak):
- I was basically able to checkout 1 item
- During processing, I was able to change the quantity of my order
- When order complete, the amount charged was for 1 item, but the final order in database was for 30 items.
Solution:
During order processing, product management in checkout page is hidden from display, preventing interaction.  
**TEST:**
1. When checking out, with metamask open, go back to webpage and see if you can manipulate the page with "Processing Order..." - you can try using css to hide the cover to see what you can manipulate.

HAMSTR-517 cover not block bottom interaction

---

hamza-client/src/lib/server/index.ts
hamza-client/src/modules/checkout/components/payment/components/payment-button/index.tsx
hamza-client/src/modules/order/components/escrow/release-escrow-dialog.tsx
hamza-client/src/modules/order/templates/escrow.tsx
hamza-client/src/modules/order/templates/processing.tsx

**Motivation**
Previously on MacGuyver, we have deployed an escrow contract to every chain that we support. Then, in order to release escrow, a customer simply connects their wallet (on the chain on which they had paid), connects to the escrow contract on that chain, and interacts with it directly to release the escrow. 
Now, we have to change that. The escrow will all be on $HOME chain, and there is no guarantee that the user has enough funds on that chain to interact with a contract on it. 
**Changes:**
1. Added backend API calls getEscrowPaymentData and releaseOrderEscrow
2. Updated escrow page to call releaseOrderEscrow when the "Release Escrow" button is clicked
3. Implemented polling with refetchInterval for escrow data to handle delays between payment and contract update …

HAMSTR-483 : Refactor Release Escrow: Frontend

---

hamza-client/src/modules/order-confirmed/index.tsx
hamza-client/src/modules/order-processing/index.tsx

**Motivation**
The cart ID is actually useful to have there, but we should just label it as what it is. The Payment address is already on the page, so doesn't need to be listed twice.
**Changes**
Just changed the label of "Payment #" to "Cart ID"

HAMSTR-518: Payment # on Payment Processing Page

---

hamza-client/src/modules/nav/templates/nav/menu-mobile/menu/wallet-info-menu-mobile.tsx

Changes:
1. Imported Zustand store (useCustomerAuthStore) in WalletInfoMobile to dynamically fetch preferred_currency_code from the store, ensuring selectedCurrency initializes correctly.
2. Updated WalletInfoMobile to use effectivePreferredCurrencyCode (combining the store value and prop fallback) to prevent selectedCurrency from resetting to ETH on re-render.
3. Updated the preferredCurrencyCode prop in CurrencySelector to use effectivePreferredCurrencyCode instead of the raw prop.
Test Steps (Mobile):
1. In the Hamza-Medusa file rainbow-provider.tsx, update const MEDUSA_SERVER_URL to {pc_ip_address}:9000.
2. In the Hamza-Backend file middlewares.ts, update const STORE_CORS to {pc_ip_address}:8000.
3. On a mobile device connected to the same network as the desktop, open Chrome and log …

HAMSTR-516 : On Mobile, Currency Selector not Working as Expected

---

hamza-client/src/modules/order/templates/cancelled.tsx
hamza-client/src/modules/order/templates/delivered.tsx
hamza-client/src/modules/order/templates/processing.tsx
hamza-client/src/modules/order/templates/refund.tsx
hamza-client/src/modules/order/templates/shipped.tsx

**Motivation**
We have to make a distinction between payment chain id and escrow chain id, for an order. The chain on which the order is in escrow used to be the same as the chain on which it was paid for, but not necessarily anymore. 
**Changes**
- The 'blockchain_data' structure of payment now has "chain_id" for backwards compatibility, in addition to the new "payment_chain_id". The former is considered to be equivalent to "escrow chain" while the latter is "payment chain".
- The frontend, when displaying the payment chain, uses the "payment_chain_id" property instead of "chain_id".
**To Test** 
- Pull the branch HAMSTR-560 for Hamza-backend
- Get some test eth on a non-sepolia testnet (I used Base Sepolia)
- Enable the same non-sepolia testnet in .env for Hamza-backend and for …

HAMSTR-560: payment chain vs. escrow chain

---

hamza-client/src/modules/order/templates/cancelled.tsx
hamza-client/src/modules/order/templates/delivered.tsx
hamza-client/src/modules/order/templates/processing.tsx
hamza-client/src/modules/order/templates/refund.tsx
hamza-client/src/modules/order/templates/shipped.tsx
hamza-client/src/modules/products/components/product-preview/components/store-banner/store-banner.tsx
hamza-client/src/modules/store/templates/store-content.tsx

**Motivation**
HNS-chat has a deeplink format. In this PR I added a 'Chat with Merchant' link to order details panel, that has that deeplink structure. 
**Changes**
Changed links to chat from store page, to follow new format
Added link to chat on order details page, for each order
**To Test**
Look at orders panel, under Order Details 
Click the link 
NOTE: requires this .env key: 
NEXT_PUBLIC_HAMZA_CHAT_LINK=https://hns-chat.hamza.market

HAMSTR-547: Deeplink to Chat

---

hamza-client/src/modules/order/components/order-overview/escrow-status.tsx
hamza-client/src/modules/order/components/order-overview/order-component.tsx
hamza-client/src/modules/order/templates/dynamic-order-status.tsx

**Motivation**
The order escrow page looks good, but I’ve noticed that it says “Delivered” for every order, even if I know the order hasn’t yet been delivered. I suspect that the “Delivered” field there may be hard-coded. 
**Changes**
The 'Delivered' was hard-coded. I changed that paymentType field to be fulfillmentStatus, and put in the order's fulfillment status as the value. 
**To Test**
- Place an async order 
- View the escrow release page for the order

HAMSTR-566: Fulfillment status on Escrow page

---

hamza-client/src/lib/util/get-product-price.ts
hamza-client/src/modules/order-processing/index.tsx

The issue is in how the ETH price is displayed. 
In the example that I reproduced, the price to pay was 0.00005195. 
The price displayed (to pay), however, was 0.00005
Paying this amount results in “partial” payment. 
So the solution is to display the price more precisely

HAMSTR-595: Error paying manually with "ETH"

---

hamza-client/src/modules/order-confirmed/index.tsx

Problem:
- Order confirmation "View Escrow" links opens up a new window/tab
- In metamask, if you are logging in using metamask browser on mobile, clicking "View Escrow" will cause open a new browser window, outside of metamask.  Most likely, that user is not logged in, and since "Escrow" page requires a logged in user, an error will occur.
Testing:
1. Make a purchase
2. On order confirmation page, click "View Escrow"
3. The user should remain in the same browser window, and redirect to Escrow page
4. (Bonus) try this on mobile with metamask wallet

HAMSTR-593 - confirmation page escrow links

---

hamza-client/src/lib/util/order-escrow.ts
hamza-client/src/modules/order-confirmed/index.tsx
hamza-client/src/modules/order-processing/components/OrderItem.tsx
hamza-client/src/modules/order/components/order-details/index.tsx
hamza-client/src/modules/order/templates/escrow.tsx

**Motivation :**
In some places, when displaying order id, we remove the “order_” prefix. However, in other places, we display the “order_” prefix. 
**Changes:**
1. Removed "order_" prefix from all order ID displays in UI components
2. Updated error messages to display order IDs without the prefix
**Testing:**
1. Go to Manage Account → Orders → View Escrow Detail - verify order IDs appear without the "order_" prefix
2. Check Payment Processor page - confirm all order ID references display without the prefix
3. Verify consistent formatting in both desktop and mobile views

HAMSTR-603 : Inconsistent Order id format ('order_')

---

hamza-client/src/app/[countryCode]/(checkout)/checkout/utils/fetch-cart-for-checkout.ts
hamza-client/src/modules/account/actions.ts
hamza-client/src/modules/checkout/components/address-modal/index.tsx
hamza-client/src/modules/checkout/components/payment/components/payment-button/index.tsx

Problem:
- When a new user creates an address and saves - the application incorrectly handles address creation (multiple addresses created), and all addresses created contains the customer_id (making the user account contain multiple addresses if they go to address book)
Note about address logic:
(1) Each time a cart has an address created, a new address record is created (even if not saved) without "customer_id" (this will ALWAYS BE CREATED for each cart)
(2) If the user decides to "save" the address, a new address record is created with the "customer_id" - so in this case, there are 2 address records created in the database
(3) If the user wants to modify the address info in the cart, it modifies the address created in (1)
(4) If the user modifies the address and selected "overwrite …

HAMSTR-529 + HAMSTR-632: address hotfix and phone number not required

---

hamza-client/src/modules/account/components/order-overview/index.tsx
hamza-client/src/modules/order/templates/escrow.tsx

Motivation
Once you get to the Release Escrow page, there’s no Back button to get back to where you were before. 
To Do: 
Add a ‘back’ navigation button or link or something 
Make it go to Manage Orders, preferably to the right tab (if easy)

HAMSTR-627 escrow back button

---

hamza-client/src/modules/order-processing/index.tsx

Problem:
Chain being displayed is always incorrect.
Testing:
1. Choose a product to buy
2. Select any chain (apart from sepolia)
3. Click on Pay with External Wallet
4. Make sure the chain is the one you selected in (2)
Bonus:
5. Pay with that chain and make sure the payment goes through

HAMSTR-664: payment processing always show sepolia as payment chain

---

hamza-client/src/modules/checkout/components/country-select/index.tsx

Problem:
When a user is not logged in -> finds item -> clicks "Buy Now" -> "Connect Wallet" -> "Add Shipping Address"
White Screen Error.
Fix:
The country select requires a region object which has a countries with undefined state until its loaded.  When no countries available, text will display "Countries loading...", until countries have completely loaded.
**TEST:**
1. Clear all cache data for your local/staging domain
2. When a user is not logged in -> finds item -> clicks "Buy Now" -> "Connect Wallet" -> "Add Shipping Address"
3. You should see "Countries loading..."
4. Then countries get populated

HAMSTR-667: handling region countries regen when user logs in

---

hamza-client/public/robots.txt
hamza-client/src/app/sitemap.ts
hamza-client/src/middleware.ts

Changes:
1. Added dynamic sitemap.ts with API calls to generate URLs for all pages
2. Added robots.txt in public directory
3. Updated middleware matcher to exclude sitemap.xml from country redirects
4. Sitemap includes: homepage, shop, stores, products, categories
Test:
1. Visit http://localhost:8000/sitemap.xml - should show XML with all pages
2. Visit http://localhost:8000/robots.txt - should show crawler rules
3. Verify sitemap contains real product/store URLs from database

HAMSTR-661 : SEO: adding robots.txt and sitemap.xml to server

---

hamza-client/src/modules/products/templates/index.tsx

In product details page add a product schema
Changes : 
1. Add generateProductJsonLd() function to generate JSON-LD structured data for products
Tests : 
1. Navigate to any product details page
2. Copy the JSON from "FINAL ENHANCED SCHEMA" in console logs
3. Paste at https://validator.schema.org/
4. Verify 0 errors and 0 warnings in validation results

HAMSTR-658 SEO: Adding Product Schema to Product Details

---

hamza-client/src/modules/products/components/product-preview/components/image-gallery/image-display/preview-gallery.tsx

**Changes**
1. Fixed image array logic in PreviewGallery component
2. Prevent gallery images from being removed when variant image is selected
3. Preserve all product images from admin panel
**Tests**
1. In the seller side, add new product with multiple images
2. Verify in the storefront all gallery images show up

HAMSL-508 : Secondary Images for Products not showing on Site

---

hamza-client/src/modules/order-processing/index.tsx

Problem:
At the bottom, Total Amount is displayed in the default currency.  When the default currency is ETH, and you are paying by bitcoin, the icon at the bottom is displaying BTC, not ETH.
**Test:**
1. Go to checkout, make sure you are paying in ETH
2. Select pay with bitcoin
3. In order processing screen, look at the bottom, Total Amount, the icon displayed should be ETH.

HAMSTR-677 - incorrect currency icon in order processing

---

hamza-client/src/app/components/schema-markup.tsx
hamza-client/src/app/layout.tsx

Adding Organization schema on homepage
Implementation:
- added organization schema for homepage only (root for site)
**Test:**
- Visit the homepage
- Make sure the Organization schema is functional
- Go to other pages, and make sure the schema doesn't display in other places

HAMSTR-660 - Organization schema on homepage

---

hamza-client/src/modules/order-processing/index.tsx

**Motivation**
When the payment is being made in bitcoin, the amount way at the very bottom of the payment processing page should show in bitcoin.

HAMSTR-687: Amount at Bottom of Payment Processing Page

---

hamza-client/src/modules/order-confirmed/index.tsx
hamza-client/src/modules/order/components/order-details.tsx
hamza-client/src/modules/order/templates/order-total-amount.tsx

**Motivation**
Once a bitcoin payment has been made by a customer, it shows up in the 
thankyou page 
orders panel 
as something other than a bitcoin payment. The fact that it has been paid in bitcoin is disguised by some other currency from which it was cross-calculated. This ain’t right. 
**Changes :** 
1. Added Bitcoin payment detection logic - Check payment metadata for currency === 'btc'
2. Updated Thank You page - Show Bitcoin icon + amount for "Total Amount Paid" section when Bitcoin payment detected
3. Updated Order Details page - Display "Bitcoin" with Bitcoin icon for "Order Chain" and show Bitcoin icon + amount for "Payment total" when Bitcoin payment detected
**Tests:**
1. Find any order
2. In that order's payment record in your local DB, set the 'metadata' field to include { …

HAMSTR-684 bitcoin payments don't show as bitcoin payments

---

hamza-client/src/modules/nav/templates/nav/menu-desktop/chain-selector-dropdown/index.tsx
hamza-client/src/modules/nav/templates/nav/menu-mobile/components/chain-selector-dropdown.tsx
hamza-client/src/modules/nav/templates/nav/menu-mobile/menu/mobile-account-menu.tsx

Problem:
When switching chains, if an error occured, the error message is in the chain switch dropdown.  But since the dropdown hides after "clicking", the user doesn't really know what happened.
Solution:
Added toast to handle error display.
**Test:**
1. (optional in local test) - change the chain id chain-select chainMap (src/modules/chain-select/index.ts) to something other non-existent id
2. launch site
3. Test the chain selector for the incorrect chain you updated in (1)
4. Error should display as a toast on the bottom right of display
NOTE: Test on mobile as well.

HAMSTR-702 - switch network error display

---

hamza-client/src/app/components/providers/rainbowkit/rainbow-provider.tsx
hamza-client/src/modules/account/components/profile/components/profile-form/components/profile-currency.tsx
hamza-client/src/modules/nav/components/nav-profile-currency/index.tsx
hamza-client/src/modules/nav/templates/nav/index.tsx
hamza-client/src/modules/nav/templates/nav/menu-mobile/mobile-nav.tsx

Problem:
Currency selector was only available after login OR in the cart page.  In order to bring currency selector into the forefront, the idea is to move the selector into the navigation bar.
Solution:
Using the code from the cart page, we can refactor and move it into the navbar for use.
**Test:**
Currency Selector before logging in:
1. Test the currency selector in desktop and mobile before logging in
Selected currency after logging in:
2. Make sure the currency stays the same as the currency before logging in

HAMSTR-691 - allow currency select before login

---

hamza-client/src/modules/order/components/transaction-details/index.tsx
hamza-client/src/modules/order/templates/order-total-amount.tsx

**Motivation**
In a customer's orders, if an order is a bitcoin payment, the USD equivalent is not showing the correct USD equivalent amount. 
**Changes**
'eth' was hard-coded as the conversion currency; should be currencyCode to account for either btc or eth. 
**To Test**
Look at any bitcoin order in customer orders panel. Verify the displayed USD equivalent price.

HAMSTR-712: Faulty BTC-USD Conversion on Orders Page

---

hamza-client/src/modules/order/templates/dynamic-order-status.tsx
hamza-client/src/modules/order/templates/orders/processing-order.tsx

Chose to go this route, when payment_status is awaiting:
**Test:**
1. Create an external wallet payment
2. Go back to order history -> processing
3. There is a button where the text "Payment Awaiting" is displayed on top right corner of an order.

HAMSTR-672 - added button for going to payment processing page from order history

---

hamza-client/src/modules/categories/components/category-banner/index.tsx

**Changes:**
1. Remove negative top margin on mobile (mt base value)
2. Add positive bottom margin on mobile (mb base value)
3. Change fixed height to auto height on mobile
4. Add min-height for mobile layout consistency
5. Reduce padding on mobile for better spacing
6. Improve text responsiveness and icon layout
**Test:**
1. Open category page on mobile device
2. Verify hero section doesn't overlap content below
3. Check text readability and spacing on mobile
4. Confirm desktop layout remains unchanged

HAMSTR-746 category page hero overlapping content mobile

---

hamza-client/src/modules/categories/components/category-grid.tsx

**Changes:**
1. Fixed background color mismatch between category icons and container
2. Set container background to #0B0A0B to match icon backgrounds
3. Removed hover:bg-zinc-900 that caused visible box effect
Test:
1. Hover over category icons on homepage
2. Verify no visible box appears around images
3. Check hover transition works smoothly

HAMSTR-756 : Background Square on Category Icons on Mouseover

---

hamza-client/src/modules/nav/templates/footer/index.tsx

**Changes:**
1. Added FaTelegram icon import to footer component
2. Added English Telegram link (https://t.me/decomnetwork)
3. Added Spanish Telegram link (https://t.me/hamza_espanol)
**Test:**
1. Verify Telegram icons display correctly in footer
2. Check both links open in new tabs

HAMSTR-763 : Links to Telegram on main page

---

hamza-client/src/config/chains/chain-config.ts

**Motivation**
In the chain selector, OP Mainnet had no logo next to it. 
---
**Changes**
It had the wrong display name (should be "OP Mainnet") 
--- 
**To Test**
- Set NEXT_PUBLIC_ALLOWED_BLOCKCHAINS=11155111,84532,56,43114,42161,10,8453,137,1
- Build frontend
- Open the chain selector 
- Make sure that all displayed chains have a logo, and especially that OP Mainnet has the round red Optimism logo
- Make sure that you can switch to all chains

HAMSTR-776: Missing Logo for OP Mainnet

---

hamza-client/src/modules/giftcards-promo/components/category-section.tsx

**Motivation**
On the Giftcards Promo landing page, we have some links that should link to subcategories of giftcards; for now though they just link to the Giftcards category page root itself. But now that we have working subcategories, we can change them to point to the appropriate subcategories.
**Changes :**
1. Updated category links to point to specific subcategories with query parameters
2. Changed "E-commerce" to "Home" category
2. Changed "Streaming" to "Entertainment" category
3. Changed "Technology" to "Digital Goods" category
4. Added href prop to CategoryCard component
**Test :**
1. Click Gaming card → should navigate to /category/gift-cards?subcategory=gaming
2. Click Home card → should navigate to /category/gift-cards?subcategory=home
3. Click Entertainment card → should …

HAMSTR-783 : Update CategoryCard to include dynamic href for category links

---

hamza-client/src/modules/store/components/store-cat-button.tsx
hamza-client/src/modules/store/components/store-search.tsx

**Changes**
1. Added horizontal scrolling to category filters when too many categories overflow the page
2. Fixed category button text centering issues for long category names
**Test**
1. Navigate to a store page with many categories and verify horizontal scrolling works

HAMSTR-796 : ReadyCashCard Store page Subcategories go off the page

---

hamza-client/src/modules/giftcards-promo/components/popular-brands-section.tsx

**Motivation**
On the giftcards promo landing page, we have brands listed; but they don't link to anything. 
**Changes**
- Created subcategories in the DB for brands (of giftcards) 
- Modified those brand links to link to the correct subcategory of giftcards

HAMSTR-784: Link brands to subcategories from Giftcards Promo Landing

---

hamza-client/src/modules/checkout/components/address-modal/index.tsx
hamza-client/src/modules/checkout/components/addresses/index.tsx
hamza-client/src/modules/checkout/components/payment/components/payment-button/index.tsx

**Motivation**
How to handle shipping addresses is still confusing to new users. 
**Changes:**
1. Made payment button clickable when address is missing - now opens address modal directly instead of being disabled
2. Changed address modal submit button to always say "Submit" instead of dynamic text (Add/Edit/Save/Overwrite)
3. Updated address section buttons to show "Add/Edit Email Address" for digital products, "Add/Edit Shipping Address" for physical products
**Test:**
1. Add items to cart without address - payment button should be clickable and open address modal when clicked
2. Open address modal - submit button should always show "Submit" regardless of add/edit/save checkbox state
3. Test with digital products - address buttons should show "Add/Edit Email Address"
4. Test with …

HAMSTR-826 : Address Handling still Confusing
